package onight.tfg.ordbgens.tlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class TLTGroupTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLT_GROUP_TYPE.GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    private String groupType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLT_GROUP_TYPE.GROUP_TYPE
     *
     * @return the value of TLT_GROUP_TYPE.GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLT_GROUP_TYPE.GROUP_TYPE
     *
     * @param groupType the value for TLT_GROUP_TYPE.GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TLTGroupTypeKey other = (TLTGroupTypeKey) that;
        return (this.getGroupType() == null ? other.getGroupType() == null : this.getGroupType().equals(other.getGroupType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupType() == null) ? 0 : getGroupType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_GROUP_TYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupType=").append(groupType);
        sb.append("]");
        return sb.toString();
    }
}