package onight.tfg.ordbgens.tlt.entity;

import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TLTIssueGenParamsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public TLTIssueGenParamsExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGenIdIsNull() {
            addCriterion("GEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andGenIdIsNotNull() {
            addCriterion("GEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGenIdEqualTo(Long value) {
            addCriterion("GEN_ID =", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdNotEqualTo(Long value) {
            addCriterion("GEN_ID <>", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdGreaterThan(Long value) {
            addCriterion("GEN_ID >", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GEN_ID >=", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdLessThan(Long value) {
            addCriterion("GEN_ID <", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdLessThanOrEqualTo(Long value) {
            addCriterion("GEN_ID <=", value, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdIn(List<Long> values) {
            addCriterion("GEN_ID in", values, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdNotIn(List<Long> values) {
            addCriterion("GEN_ID not in", values, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdBetween(Long value1, Long value2) {
            addCriterion("GEN_ID between", value1, value2, "genId");
            return (Criteria) this;
        }

        public Criteria andGenIdNotBetween(Long value1, Long value2) {
            addCriterion("GEN_ID not between", value1, value2, "genId");
            return (Criteria) this;
        }

        public Criteria andLtypeIsNull() {
            addCriterion("LTYPE is null");
            return (Criteria) this;
        }

        public Criteria andLtypeIsNotNull() {
            addCriterion("LTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLtypeEqualTo(String value) {
            addCriterion("LTYPE =", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotEqualTo(String value) {
            addCriterion("LTYPE <>", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeGreaterThan(String value) {
            addCriterion("LTYPE >", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeGreaterThanOrEqualTo(String value) {
            addCriterion("LTYPE >=", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLessThan(String value) {
            addCriterion("LTYPE <", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLessThanOrEqualTo(String value) {
            addCriterion("LTYPE <=", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLike(String value) {
            addCriterion("LTYPE like", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotLike(String value) {
            addCriterion("LTYPE not like", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeIn(List<String> values) {
            addCriterion("LTYPE in", values, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotIn(List<String> values) {
            addCriterion("LTYPE not in", values, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeBetween(String value1, String value2) {
            addCriterion("LTYPE between", value1, value2, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotBetween(String value1, String value2) {
            addCriterion("LTYPE not between", value1, value2, "ltype");
            return (Criteria) this;
        }

        public Criteria andSaleStimeIsNull() {
            addCriterion("SALE_STIME is null");
            return (Criteria) this;
        }

        public Criteria andSaleStimeIsNotNull() {
            addCriterion("SALE_STIME is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStimeEqualTo(String value) {
            addCriterion("SALE_STIME =", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeNotEqualTo(String value) {
            addCriterion("SALE_STIME <>", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeGreaterThan(String value) {
            addCriterion("SALE_STIME >", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeGreaterThanOrEqualTo(String value) {
            addCriterion("SALE_STIME >=", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeLessThan(String value) {
            addCriterion("SALE_STIME <", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeLessThanOrEqualTo(String value) {
            addCriterion("SALE_STIME <=", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeLike(String value) {
            addCriterion("SALE_STIME like", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeNotLike(String value) {
            addCriterion("SALE_STIME not like", value, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeIn(List<String> values) {
            addCriterion("SALE_STIME in", values, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeNotIn(List<String> values) {
            addCriterion("SALE_STIME not in", values, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeBetween(String value1, String value2) {
            addCriterion("SALE_STIME between", value1, value2, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleStimeNotBetween(String value1, String value2) {
            addCriterion("SALE_STIME not between", value1, value2, "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeIsNull() {
            addCriterion("SALE_ETIME is null");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeIsNotNull() {
            addCriterion("SALE_ETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeEqualTo(String value) {
            addCriterion("SALE_ETIME =", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeNotEqualTo(String value) {
            addCriterion("SALE_ETIME <>", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeGreaterThan(String value) {
            addCriterion("SALE_ETIME >", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeGreaterThanOrEqualTo(String value) {
            addCriterion("SALE_ETIME >=", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeLessThan(String value) {
            addCriterion("SALE_ETIME <", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeLessThanOrEqualTo(String value) {
            addCriterion("SALE_ETIME <=", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeLike(String value) {
            addCriterion("SALE_ETIME like", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeNotLike(String value) {
            addCriterion("SALE_ETIME not like", value, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeIn(List<String> values) {
            addCriterion("SALE_ETIME in", values, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeNotIn(List<String> values) {
            addCriterion("SALE_ETIME not in", values, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeBetween(String value1, String value2) {
            addCriterion("SALE_ETIME between", value1, value2, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeNotBetween(String value1, String value2) {
            addCriterion("SALE_ETIME not between", value1, value2, "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeIsNull() {
            addCriterion("SALE_FI_ETIME is null");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeIsNotNull() {
            addCriterion("SALE_FI_ETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeEqualTo(String value) {
            addCriterion("SALE_FI_ETIME =", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeNotEqualTo(String value) {
            addCriterion("SALE_FI_ETIME <>", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeGreaterThan(String value) {
            addCriterion("SALE_FI_ETIME >", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeGreaterThanOrEqualTo(String value) {
            addCriterion("SALE_FI_ETIME >=", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeLessThan(String value) {
            addCriterion("SALE_FI_ETIME <", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeLessThanOrEqualTo(String value) {
            addCriterion("SALE_FI_ETIME <=", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeLike(String value) {
            addCriterion("SALE_FI_ETIME like", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeNotLike(String value) {
            addCriterion("SALE_FI_ETIME not like", value, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeIn(List<String> values) {
            addCriterion("SALE_FI_ETIME in", values, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeNotIn(List<String> values) {
            addCriterion("SALE_FI_ETIME not in", values, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeBetween(String value1, String value2) {
            addCriterion("SALE_FI_ETIME between", value1, value2, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeNotBetween(String value1, String value2) {
            addCriterion("SALE_FI_ETIME not between", value1, value2, "saleFiEtime");
            return (Criteria) this;
        }

        public Criteria andSaleCycleIsNull() {
            addCriterion("SALE_CYCLE is null");
            return (Criteria) this;
        }

        public Criteria andSaleCycleIsNotNull() {
            addCriterion("SALE_CYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andSaleCycleEqualTo(Integer value) {
            addCriterion("SALE_CYCLE =", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleNotEqualTo(Integer value) {
            addCriterion("SALE_CYCLE <>", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleGreaterThan(Integer value) {
            addCriterion("SALE_CYCLE >", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("SALE_CYCLE >=", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleLessThan(Integer value) {
            addCriterion("SALE_CYCLE <", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleLessThanOrEqualTo(Integer value) {
            addCriterion("SALE_CYCLE <=", value, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleIn(List<Integer> values) {
            addCriterion("SALE_CYCLE in", values, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleNotIn(List<Integer> values) {
            addCriterion("SALE_CYCLE not in", values, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleBetween(Integer value1, Integer value2) {
            addCriterion("SALE_CYCLE between", value1, value2, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andSaleCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("SALE_CYCLE not between", value1, value2, "saleCycle");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurIsNull() {
            addCriterion("WAIT_RL_DUR is null");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurIsNotNull() {
            addCriterion("WAIT_RL_DUR is not null");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurEqualTo(Integer value) {
            addCriterion("WAIT_RL_DUR =", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurNotEqualTo(Integer value) {
            addCriterion("WAIT_RL_DUR <>", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurGreaterThan(Integer value) {
            addCriterion("WAIT_RL_DUR >", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurGreaterThanOrEqualTo(Integer value) {
            addCriterion("WAIT_RL_DUR >=", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurLessThan(Integer value) {
            addCriterion("WAIT_RL_DUR <", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurLessThanOrEqualTo(Integer value) {
            addCriterion("WAIT_RL_DUR <=", value, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurIn(List<Integer> values) {
            addCriterion("WAIT_RL_DUR in", values, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurNotIn(List<Integer> values) {
            addCriterion("WAIT_RL_DUR not in", values, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurBetween(Integer value1, Integer value2) {
            addCriterion("WAIT_RL_DUR between", value1, value2, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andWaitRlDurNotBetween(Integer value1, Integer value2) {
            addCriterion("WAIT_RL_DUR not between", value1, value2, "waitRlDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurIsNull() {
            addCriterion("CANCEL_DUR is null");
            return (Criteria) this;
        }

        public Criteria andCancelDurIsNotNull() {
            addCriterion("CANCEL_DUR is not null");
            return (Criteria) this;
        }

        public Criteria andCancelDurEqualTo(Integer value) {
            addCriterion("CANCEL_DUR =", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurNotEqualTo(Integer value) {
            addCriterion("CANCEL_DUR <>", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurGreaterThan(Integer value) {
            addCriterion("CANCEL_DUR >", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurGreaterThanOrEqualTo(Integer value) {
            addCriterion("CANCEL_DUR >=", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurLessThan(Integer value) {
            addCriterion("CANCEL_DUR <", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurLessThanOrEqualTo(Integer value) {
            addCriterion("CANCEL_DUR <=", value, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurIn(List<Integer> values) {
            addCriterion("CANCEL_DUR in", values, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurNotIn(List<Integer> values) {
            addCriterion("CANCEL_DUR not in", values, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurBetween(Integer value1, Integer value2) {
            addCriterion("CANCEL_DUR between", value1, value2, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andCancelDurNotBetween(Integer value1, Integer value2) {
            addCriterion("CANCEL_DUR not between", value1, value2, "cancelDur");
            return (Criteria) this;
        }

        public Criteria andInputDurIsNull() {
            addCriterion("INPUT_DUR is null");
            return (Criteria) this;
        }

        public Criteria andInputDurIsNotNull() {
            addCriterion("INPUT_DUR is not null");
            return (Criteria) this;
        }

        public Criteria andInputDurEqualTo(Integer value) {
            addCriterion("INPUT_DUR =", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurNotEqualTo(Integer value) {
            addCriterion("INPUT_DUR <>", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurGreaterThan(Integer value) {
            addCriterion("INPUT_DUR >", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurGreaterThanOrEqualTo(Integer value) {
            addCriterion("INPUT_DUR >=", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurLessThan(Integer value) {
            addCriterion("INPUT_DUR <", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurLessThanOrEqualTo(Integer value) {
            addCriterion("INPUT_DUR <=", value, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurIn(List<Integer> values) {
            addCriterion("INPUT_DUR in", values, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurNotIn(List<Integer> values) {
            addCriterion("INPUT_DUR not in", values, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurBetween(Integer value1, Integer value2) {
            addCriterion("INPUT_DUR between", value1, value2, "inputDur");
            return (Criteria) this;
        }

        public Criteria andInputDurNotBetween(Integer value1, Integer value2) {
            addCriterion("INPUT_DUR not between", value1, value2, "inputDur");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Byte value) {
            addCriterion("SORT =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Byte value) {
            addCriterion("SORT <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Byte value) {
            addCriterion("SORT >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Byte value) {
            addCriterion("SORT >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Byte value) {
            addCriterion("SORT <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Byte value) {
            addCriterion("SORT <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Byte> values) {
            addCriterion("SORT in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Byte> values) {
            addCriterion("SORT not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Byte value1, Byte value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Byte value1, Byte value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("ENABLE =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("ENABLE <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("ENABLE >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ENABLE >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("ENABLE <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("ENABLE <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("ENABLE in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("ENABLE not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("ENABLE between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ENABLE not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andLtypeLikeInsensitive(String value) {
            addCriterion("upper(LTYPE) like", value.toUpperCase(), "ltype");
            return (Criteria) this;
        }

        public Criteria andSaleStimeLikeInsensitive(String value) {
            addCriterion("upper(SALE_STIME) like", value.toUpperCase(), "saleStime");
            return (Criteria) this;
        }

        public Criteria andSaleEtimeLikeInsensitive(String value) {
            addCriterion("upper(SALE_ETIME) like", value.toUpperCase(), "saleEtime");
            return (Criteria) this;
        }

        public Criteria andSaleFiEtimeLikeInsensitive(String value) {
            addCriterion("upper(SALE_FI_ETIME) like", value.toUpperCase(), "saleFiEtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 07 21:59:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_ISSUE_GEN_PARAMS
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}