package onight.tfg.ordbgens.tlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TLTLtypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public TLTLtypeExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLtypeIsNull() {
            addCriterion("LTYPE is null");
            return (Criteria) this;
        }

        public Criteria andLtypeIsNotNull() {
            addCriterion("LTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLtypeEqualTo(String value) {
            addCriterion("LTYPE =", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotEqualTo(String value) {
            addCriterion("LTYPE <>", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeGreaterThan(String value) {
            addCriterion("LTYPE >", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeGreaterThanOrEqualTo(String value) {
            addCriterion("LTYPE >=", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLessThan(String value) {
            addCriterion("LTYPE <", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLessThanOrEqualTo(String value) {
            addCriterion("LTYPE <=", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeLike(String value) {
            addCriterion("LTYPE like", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotLike(String value) {
            addCriterion("LTYPE not like", value, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeIn(List<String> values) {
            addCriterion("LTYPE in", values, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotIn(List<String> values) {
            addCriterion("LTYPE not in", values, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeBetween(String value1, String value2) {
            addCriterion("LTYPE between", value1, value2, "ltype");
            return (Criteria) this;
        }

        public Criteria andLtypeNotBetween(String value1, String value2) {
            addCriterion("LTYPE not between", value1, value2, "ltype");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNull() {
            addCriterion("GROUP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNotNull() {
            addCriterion("GROUP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeEqualTo(String value) {
            addCriterion("GROUP_TYPE =", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotEqualTo(String value) {
            addCriterion("GROUP_TYPE <>", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThan(String value) {
            addCriterion("GROUP_TYPE >", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE >=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThan(String value) {
            addCriterion("GROUP_TYPE <", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThanOrEqualTo(String value) {
            addCriterion("GROUP_TYPE <=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLike(String value) {
            addCriterion("GROUP_TYPE like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotLike(String value) {
            addCriterion("GROUP_TYPE not like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIn(List<String> values) {
            addCriterion("GROUP_TYPE in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotIn(List<String> values) {
            addCriterion("GROUP_TYPE not in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotBetween(String value1, String value2) {
            addCriterion("GROUP_TYPE not between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andCnNameIsNull() {
            addCriterion("CN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCnNameIsNotNull() {
            addCriterion("CN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCnNameEqualTo(String value) {
            addCriterion("CN_NAME =", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotEqualTo(String value) {
            addCriterion("CN_NAME <>", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameGreaterThan(String value) {
            addCriterion("CN_NAME >", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameGreaterThanOrEqualTo(String value) {
            addCriterion("CN_NAME >=", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLessThan(String value) {
            addCriterion("CN_NAME <", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLessThanOrEqualTo(String value) {
            addCriterion("CN_NAME <=", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameLike(String value) {
            addCriterion("CN_NAME like", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotLike(String value) {
            addCriterion("CN_NAME not like", value, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameIn(List<String> values) {
            addCriterion("CN_NAME in", values, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotIn(List<String> values) {
            addCriterion("CN_NAME not in", values, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameBetween(String value1, String value2) {
            addCriterion("CN_NAME between", value1, value2, "cnName");
            return (Criteria) this;
        }

        public Criteria andCnNameNotBetween(String value1, String value2) {
            addCriterion("CN_NAME not between", value1, value2, "cnName");
            return (Criteria) this;
        }

        public Criteria andEnNameIsNull() {
            addCriterion("EN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEnNameIsNotNull() {
            addCriterion("EN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEnNameEqualTo(String value) {
            addCriterion("EN_NAME =", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameNotEqualTo(String value) {
            addCriterion("EN_NAME <>", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameGreaterThan(String value) {
            addCriterion("EN_NAME >", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameGreaterThanOrEqualTo(String value) {
            addCriterion("EN_NAME >=", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameLessThan(String value) {
            addCriterion("EN_NAME <", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameLessThanOrEqualTo(String value) {
            addCriterion("EN_NAME <=", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameLike(String value) {
            addCriterion("EN_NAME like", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameNotLike(String value) {
            addCriterion("EN_NAME not like", value, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameIn(List<String> values) {
            addCriterion("EN_NAME in", values, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameNotIn(List<String> values) {
            addCriterion("EN_NAME not in", values, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameBetween(String value1, String value2) {
            addCriterion("EN_NAME between", value1, value2, "enName");
            return (Criteria) this;
        }

        public Criteria andEnNameNotBetween(String value1, String value2) {
            addCriterion("EN_NAME not between", value1, value2, "enName");
            return (Criteria) this;
        }

        public Criteria andCodeListIsNull() {
            addCriterion("CODE_LIST is null");
            return (Criteria) this;
        }

        public Criteria andCodeListIsNotNull() {
            addCriterion("CODE_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andCodeListEqualTo(String value) {
            addCriterion("CODE_LIST =", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListNotEqualTo(String value) {
            addCriterion("CODE_LIST <>", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListGreaterThan(String value) {
            addCriterion("CODE_LIST >", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_LIST >=", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListLessThan(String value) {
            addCriterion("CODE_LIST <", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListLessThanOrEqualTo(String value) {
            addCriterion("CODE_LIST <=", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListLike(String value) {
            addCriterion("CODE_LIST like", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListNotLike(String value) {
            addCriterion("CODE_LIST not like", value, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListIn(List<String> values) {
            addCriterion("CODE_LIST in", values, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListNotIn(List<String> values) {
            addCriterion("CODE_LIST not in", values, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListBetween(String value1, String value2) {
            addCriterion("CODE_LIST between", value1, value2, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeListNotBetween(String value1, String value2) {
            addCriterion("CODE_LIST not between", value1, value2, "codeList");
            return (Criteria) this;
        }

        public Criteria andCodeLenIsNull() {
            addCriterion("CODE_LEN is null");
            return (Criteria) this;
        }

        public Criteria andCodeLenIsNotNull() {
            addCriterion("CODE_LEN is not null");
            return (Criteria) this;
        }

        public Criteria andCodeLenEqualTo(Integer value) {
            addCriterion("CODE_LEN =", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenNotEqualTo(Integer value) {
            addCriterion("CODE_LEN <>", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenGreaterThan(Integer value) {
            addCriterion("CODE_LEN >", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenGreaterThanOrEqualTo(Integer value) {
            addCriterion("CODE_LEN >=", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenLessThan(Integer value) {
            addCriterion("CODE_LEN <", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenLessThanOrEqualTo(Integer value) {
            addCriterion("CODE_LEN <=", value, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenIn(List<Integer> values) {
            addCriterion("CODE_LEN in", values, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenNotIn(List<Integer> values) {
            addCriterion("CODE_LEN not in", values, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenBetween(Integer value1, Integer value2) {
            addCriterion("CODE_LEN between", value1, value2, "codeLen");
            return (Criteria) this;
        }

        public Criteria andCodeLenNotBetween(Integer value1, Integer value2) {
            addCriterion("CODE_LEN not between", value1, value2, "codeLen");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Byte value) {
            addCriterion("SORT =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Byte value) {
            addCriterion("SORT <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Byte value) {
            addCriterion("SORT >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Byte value) {
            addCriterion("SORT >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Byte value) {
            addCriterion("SORT <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Byte value) {
            addCriterion("SORT <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Byte> values) {
            addCriterion("SORT in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Byte> values) {
            addCriterion("SORT not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Byte value1, Byte value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Byte value1, Byte value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("ENABLE =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("ENABLE <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("ENABLE >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ENABLE >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("ENABLE <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("ENABLE <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("ENABLE in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("ENABLE not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("ENABLE between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ENABLE not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIsNull() {
            addCriterion("DELAY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIsNotNull() {
            addCriterion("DELAY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDelayTimeEqualTo(Integer value) {
            addCriterion("DELAY_TIME =", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotEqualTo(Integer value) {
            addCriterion("DELAY_TIME <>", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeGreaterThan(Integer value) {
            addCriterion("DELAY_TIME >", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELAY_TIME >=", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeLessThan(Integer value) {
            addCriterion("DELAY_TIME <", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeLessThanOrEqualTo(Integer value) {
            addCriterion("DELAY_TIME <=", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIn(List<Integer> values) {
            addCriterion("DELAY_TIME in", values, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotIn(List<Integer> values) {
            addCriterion("DELAY_TIME not in", values, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeBetween(Integer value1, Integer value2) {
            addCriterion("DELAY_TIME between", value1, value2, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("DELAY_TIME not between", value1, value2, "delayTime");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountIsNull() {
            addCriterion("CATCH_CODE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountIsNotNull() {
            addCriterion("CATCH_CODE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountEqualTo(Integer value) {
            addCriterion("CATCH_CODE_COUNT =", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountNotEqualTo(Integer value) {
            addCriterion("CATCH_CODE_COUNT <>", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountGreaterThan(Integer value) {
            addCriterion("CATCH_CODE_COUNT >", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("CATCH_CODE_COUNT >=", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountLessThan(Integer value) {
            addCriterion("CATCH_CODE_COUNT <", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountLessThanOrEqualTo(Integer value) {
            addCriterion("CATCH_CODE_COUNT <=", value, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountIn(List<Integer> values) {
            addCriterion("CATCH_CODE_COUNT in", values, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountNotIn(List<Integer> values) {
            addCriterion("CATCH_CODE_COUNT not in", values, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountBetween(Integer value1, Integer value2) {
            addCriterion("CATCH_CODE_COUNT between", value1, value2, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("CATCH_CODE_COUNT not between", value1, value2, "catchCodeCount");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalIsNull() {
            addCriterion("CATCH_CODE_INTERVAL is null");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalIsNotNull() {
            addCriterion("CATCH_CODE_INTERVAL is not null");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalEqualTo(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL =", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalNotEqualTo(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL <>", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalGreaterThan(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL >", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL >=", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalLessThan(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL <", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("CATCH_CODE_INTERVAL <=", value, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalIn(List<Integer> values) {
            addCriterion("CATCH_CODE_INTERVAL in", values, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalNotIn(List<Integer> values) {
            addCriterion("CATCH_CODE_INTERVAL not in", values, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalBetween(Integer value1, Integer value2) {
            addCriterion("CATCH_CODE_INTERVAL between", value1, value2, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andCatchCodeIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("CATCH_CODE_INTERVAL not between", value1, value2, "catchCodeInterval");
            return (Criteria) this;
        }

        public Criteria andMinLeftIsNull() {
            addCriterion("MIN_LEFT is null");
            return (Criteria) this;
        }

        public Criteria andMinLeftIsNotNull() {
            addCriterion("MIN_LEFT is not null");
            return (Criteria) this;
        }

        public Criteria andMinLeftEqualTo(Float value) {
            addCriterion("MIN_LEFT =", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftNotEqualTo(Float value) {
            addCriterion("MIN_LEFT <>", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftGreaterThan(Float value) {
            addCriterion("MIN_LEFT >", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftGreaterThanOrEqualTo(Float value) {
            addCriterion("MIN_LEFT >=", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftLessThan(Float value) {
            addCriterion("MIN_LEFT <", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftLessThanOrEqualTo(Float value) {
            addCriterion("MIN_LEFT <=", value, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftIn(List<Float> values) {
            addCriterion("MIN_LEFT in", values, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftNotIn(List<Float> values) {
            addCriterion("MIN_LEFT not in", values, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftBetween(Float value1, Float value2) {
            addCriterion("MIN_LEFT between", value1, value2, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinLeftNotBetween(Float value1, Float value2) {
            addCriterion("MIN_LEFT not between", value1, value2, "minLeft");
            return (Criteria) this;
        }

        public Criteria andMinSpreadIsNull() {
            addCriterion("MIN_SPREAD is null");
            return (Criteria) this;
        }

        public Criteria andMinSpreadIsNotNull() {
            addCriterion("MIN_SPREAD is not null");
            return (Criteria) this;
        }

        public Criteria andMinSpreadEqualTo(Float value) {
            addCriterion("MIN_SPREAD =", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadNotEqualTo(Float value) {
            addCriterion("MIN_SPREAD <>", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadGreaterThan(Float value) {
            addCriterion("MIN_SPREAD >", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadGreaterThanOrEqualTo(Float value) {
            addCriterion("MIN_SPREAD >=", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadLessThan(Float value) {
            addCriterion("MIN_SPREAD <", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadLessThanOrEqualTo(Float value) {
            addCriterion("MIN_SPREAD <=", value, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadIn(List<Float> values) {
            addCriterion("MIN_SPREAD in", values, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadNotIn(List<Float> values) {
            addCriterion("MIN_SPREAD not in", values, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadBetween(Float value1, Float value2) {
            addCriterion("MIN_SPREAD between", value1, value2, "minSpread");
            return (Criteria) this;
        }

        public Criteria andMinSpreadNotBetween(Float value1, Float value2) {
            addCriterion("MIN_SPREAD not between", value1, value2, "minSpread");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtIsNull() {
            addCriterion("ISSUE_NO_FMT is null");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtIsNotNull() {
            addCriterion("ISSUE_NO_FMT is not null");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtEqualTo(String value) {
            addCriterion("ISSUE_NO_FMT =", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtNotEqualTo(String value) {
            addCriterion("ISSUE_NO_FMT <>", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtGreaterThan(String value) {
            addCriterion("ISSUE_NO_FMT >", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUE_NO_FMT >=", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtLessThan(String value) {
            addCriterion("ISSUE_NO_FMT <", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtLessThanOrEqualTo(String value) {
            addCriterion("ISSUE_NO_FMT <=", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtLike(String value) {
            addCriterion("ISSUE_NO_FMT like", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtNotLike(String value) {
            addCriterion("ISSUE_NO_FMT not like", value, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtIn(List<String> values) {
            addCriterion("ISSUE_NO_FMT in", values, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtNotIn(List<String> values) {
            addCriterion("ISSUE_NO_FMT not in", values, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtBetween(String value1, String value2) {
            addCriterion("ISSUE_NO_FMT between", value1, value2, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtNotBetween(String value1, String value2) {
            addCriterion("ISSUE_NO_FMT not between", value1, value2, "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andClearYmdIsNull() {
            addCriterion("CLEAR_YMD is null");
            return (Criteria) this;
        }

        public Criteria andClearYmdIsNotNull() {
            addCriterion("CLEAR_YMD is not null");
            return (Criteria) this;
        }

        public Criteria andClearYmdEqualTo(String value) {
            addCriterion("CLEAR_YMD =", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdNotEqualTo(String value) {
            addCriterion("CLEAR_YMD <>", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdGreaterThan(String value) {
            addCriterion("CLEAR_YMD >", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdGreaterThanOrEqualTo(String value) {
            addCriterion("CLEAR_YMD >=", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdLessThan(String value) {
            addCriterion("CLEAR_YMD <", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdLessThanOrEqualTo(String value) {
            addCriterion("CLEAR_YMD <=", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdLike(String value) {
            addCriterion("CLEAR_YMD like", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdNotLike(String value) {
            addCriterion("CLEAR_YMD not like", value, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdIn(List<String> values) {
            addCriterion("CLEAR_YMD in", values, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdNotIn(List<String> values) {
            addCriterion("CLEAR_YMD not in", values, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdBetween(String value1, String value2) {
            addCriterion("CLEAR_YMD between", value1, value2, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andClearYmdNotBetween(String value1, String value2) {
            addCriterion("CLEAR_YMD not between", value1, value2, "clearYmd");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleIsNull() {
            addCriterion("LOTTERY_CYCLE is null");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleIsNotNull() {
            addCriterion("LOTTERY_CYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleEqualTo(String value) {
            addCriterion("LOTTERY_CYCLE =", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleNotEqualTo(String value) {
            addCriterion("LOTTERY_CYCLE <>", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleGreaterThan(String value) {
            addCriterion("LOTTERY_CYCLE >", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleGreaterThanOrEqualTo(String value) {
            addCriterion("LOTTERY_CYCLE >=", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleLessThan(String value) {
            addCriterion("LOTTERY_CYCLE <", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleLessThanOrEqualTo(String value) {
            addCriterion("LOTTERY_CYCLE <=", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleLike(String value) {
            addCriterion("LOTTERY_CYCLE like", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleNotLike(String value) {
            addCriterion("LOTTERY_CYCLE not like", value, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleIn(List<String> values) {
            addCriterion("LOTTERY_CYCLE in", values, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleNotIn(List<String> values) {
            addCriterion("LOTTERY_CYCLE not in", values, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleBetween(String value1, String value2) {
            addCriterion("LOTTERY_CYCLE between", value1, value2, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleNotBetween(String value1, String value2) {
            addCriterion("LOTTERY_CYCLE not between", value1, value2, "lotteryCycle");
            return (Criteria) this;
        }

        public Criteria andCloseStimeIsNull() {
            addCriterion("CLOSE_STIME is null");
            return (Criteria) this;
        }

        public Criteria andCloseStimeIsNotNull() {
            addCriterion("CLOSE_STIME is not null");
            return (Criteria) this;
        }

        public Criteria andCloseStimeEqualTo(Date value) {
            addCriterion("CLOSE_STIME =", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeNotEqualTo(Date value) {
            addCriterion("CLOSE_STIME <>", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeGreaterThan(Date value) {
            addCriterion("CLOSE_STIME >", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CLOSE_STIME >=", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeLessThan(Date value) {
            addCriterion("CLOSE_STIME <", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeLessThanOrEqualTo(Date value) {
            addCriterion("CLOSE_STIME <=", value, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeIn(List<Date> values) {
            addCriterion("CLOSE_STIME in", values, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeNotIn(List<Date> values) {
            addCriterion("CLOSE_STIME not in", values, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeBetween(Date value1, Date value2) {
            addCriterion("CLOSE_STIME between", value1, value2, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseStimeNotBetween(Date value1, Date value2) {
            addCriterion("CLOSE_STIME not between", value1, value2, "closeStime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeIsNull() {
            addCriterion("CLOSE_ETIME is null");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeIsNotNull() {
            addCriterion("CLOSE_ETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeEqualTo(Date value) {
            addCriterion("CLOSE_ETIME =", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeNotEqualTo(Date value) {
            addCriterion("CLOSE_ETIME <>", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeGreaterThan(Date value) {
            addCriterion("CLOSE_ETIME >", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CLOSE_ETIME >=", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeLessThan(Date value) {
            addCriterion("CLOSE_ETIME <", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeLessThanOrEqualTo(Date value) {
            addCriterion("CLOSE_ETIME <=", value, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeIn(List<Date> values) {
            addCriterion("CLOSE_ETIME in", values, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeNotIn(List<Date> values) {
            addCriterion("CLOSE_ETIME not in", values, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeBetween(Date value1, Date value2) {
            addCriterion("CLOSE_ETIME between", value1, value2, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andCloseEtimeNotBetween(Date value1, Date value2) {
            addCriterion("CLOSE_ETIME not between", value1, value2, "closeEtime");
            return (Criteria) this;
        }

        public Criteria andRebateIsNull() {
            addCriterion("REBATE is null");
            return (Criteria) this;
        }

        public Criteria andRebateIsNotNull() {
            addCriterion("REBATE is not null");
            return (Criteria) this;
        }

        public Criteria andRebateEqualTo(Float value) {
            addCriterion("REBATE =", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateNotEqualTo(Float value) {
            addCriterion("REBATE <>", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateGreaterThan(Float value) {
            addCriterion("REBATE >", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateGreaterThanOrEqualTo(Float value) {
            addCriterion("REBATE >=", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateLessThan(Float value) {
            addCriterion("REBATE <", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateLessThanOrEqualTo(Float value) {
            addCriterion("REBATE <=", value, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateIn(List<Float> values) {
            addCriterion("REBATE in", values, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateNotIn(List<Float> values) {
            addCriterion("REBATE not in", values, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateBetween(Float value1, Float value2) {
            addCriterion("REBATE between", value1, value2, "rebate");
            return (Criteria) this;
        }

        public Criteria andRebateNotBetween(Float value1, Float value2) {
            addCriterion("REBATE not between", value1, value2, "rebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateIsNull() {
            addCriterion("DELO_REBATE is null");
            return (Criteria) this;
        }

        public Criteria andDeloRebateIsNotNull() {
            addCriterion("DELO_REBATE is not null");
            return (Criteria) this;
        }

        public Criteria andDeloRebateEqualTo(Float value) {
            addCriterion("DELO_REBATE =", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateNotEqualTo(Float value) {
            addCriterion("DELO_REBATE <>", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateGreaterThan(Float value) {
            addCriterion("DELO_REBATE >", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateGreaterThanOrEqualTo(Float value) {
            addCriterion("DELO_REBATE >=", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateLessThan(Float value) {
            addCriterion("DELO_REBATE <", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateLessThanOrEqualTo(Float value) {
            addCriterion("DELO_REBATE <=", value, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateIn(List<Float> values) {
            addCriterion("DELO_REBATE in", values, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateNotIn(List<Float> values) {
            addCriterion("DELO_REBATE not in", values, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateBetween(Float value1, Float value2) {
            addCriterion("DELO_REBATE between", value1, value2, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andDeloRebateNotBetween(Float value1, Float value2) {
            addCriterion("DELO_REBATE not between", value1, value2, "deloRebate");
            return (Criteria) this;
        }

        public Criteria andLtypeLikeInsensitive(String value) {
            addCriterion("upper(LTYPE) like", value.toUpperCase(), "ltype");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLikeInsensitive(String value) {
            addCriterion("upper(GROUP_TYPE) like", value.toUpperCase(), "groupType");
            return (Criteria) this;
        }

        public Criteria andCnNameLikeInsensitive(String value) {
            addCriterion("upper(CN_NAME) like", value.toUpperCase(), "cnName");
            return (Criteria) this;
        }

        public Criteria andEnNameLikeInsensitive(String value) {
            addCriterion("upper(EN_NAME) like", value.toUpperCase(), "enName");
            return (Criteria) this;
        }

        public Criteria andCodeListLikeInsensitive(String value) {
            addCriterion("upper(CODE_LIST) like", value.toUpperCase(), "codeList");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(REMARK) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        public Criteria andIssueNoFmtLikeInsensitive(String value) {
            addCriterion("upper(ISSUE_NO_FMT) like", value.toUpperCase(), "issueNoFmt");
            return (Criteria) this;
        }

        public Criteria andClearYmdLikeInsensitive(String value) {
            addCriterion("upper(CLEAR_YMD) like", value.toUpperCase(), "clearYmd");
            return (Criteria) this;
        }

        public Criteria andLotteryCycleLikeInsensitive(String value) {
            addCriterion("upper(LOTTERY_CYCLE) like", value.toUpperCase(), "lotteryCycle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 07 21:59:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLT_LTYPE
     *
     * @mbggenerated Thu Apr 07 21:59:26 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}