/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brew' at '16-1-23 上午10:21' with Gradle 2.10
 *
 * @author brew, @date 16-1-23 上午10:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
