package onight.tfg.ordbgens.tfc.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import onight.tfg.ordbgens.tfc.entity.TFCOrder;
import onight.tfg.ordbgens.tfc.entity.TFCOrderExample.Criteria;
import onight.tfg.ordbgens.tfc.entity.TFCOrderExample.Criterion;
import onight.tfg.ordbgens.tfc.entity.TFCOrderExample;

public class TFCOrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String countByExample(TFCOrderExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("TFC_ORDER");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String deleteByExample(TFCOrderExample example) {
        BEGIN();
        DELETE_FROM("TFC_ORDER");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String insertSelective(TFCOrder record) {
        BEGIN();
        INSERT_INTO("TFC_ORDER");
        
        if (record.getOrderId() != null) {
            VALUES("ORDER_ID", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            VALUES("USER_ID", "#{userId,jdbcType=BIGINT}");
        }
        
        if (record.getOrderStatus() != null) {
            VALUES("ORDER_STATUS", "#{orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getItemId() != null) {
            VALUES("ITEM_ID", "#{itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinNum() != null) {
            VALUES("COIN_NUM", "#{coinNum,jdbcType=BIGINT}");
        }
        
        if (record.getStorageTime() != null) {
            VALUES("STORAGE_TIME", "#{storageTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHandleTime() != null) {
            VALUES("HANDLE_TIME", "#{handleTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String selectByExample(TFCOrderExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ORDER_ID");
        } else {
            SELECT("ORDER_ID");
        }
        SELECT("USER_ID");
        SELECT("ORDER_STATUS");
        SELECT("ITEM_ID");
        SELECT("COIN_NUM");
        SELECT("STORAGE_TIME");
        SELECT("HANDLE_TIME");
        FROM("TFC_ORDER");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				applyWhere(example, false);
		}
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TFCOrder record = (TFCOrder) parameter.get("record");
        TFCOrderExample example = (TFCOrderExample) parameter.get("example");
        
        BEGIN();
        UPDATE("TFC_ORDER");
        
        if (record.getOrderId() != null) {
            SET("ORDER_ID = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{record.userId,jdbcType=BIGINT}");
        }
        
        if (record.getOrderStatus() != null) {
            SET("ORDER_STATUS = #{record.orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getItemId() != null) {
            SET("ITEM_ID = #{record.itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinNum() != null) {
            SET("COIN_NUM = #{record.coinNum,jdbcType=BIGINT}");
        }
        
        if (record.getStorageTime() != null) {
            SET("STORAGE_TIME = #{record.storageTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHandleTime() != null) {
            SET("HANDLE_TIME = #{record.handleTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("TFC_ORDER");
        
        SET("ORDER_ID = #{record.orderId,jdbcType=VARCHAR}");
        SET("USER_ID = #{record.userId,jdbcType=BIGINT}");
        SET("ORDER_STATUS = #{record.orderStatus,jdbcType=INTEGER}");
        SET("ITEM_ID = #{record.itemId,jdbcType=VARCHAR}");
        SET("COIN_NUM = #{record.coinNum,jdbcType=BIGINT}");
        SET("STORAGE_TIME = #{record.storageTime,jdbcType=TIMESTAMP}");
        SET("HANDLE_TIME = #{record.handleTime,jdbcType=TIMESTAMP}");
        
        TFCOrderExample example = (TFCOrderExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String updateByPrimaryKeySelective(TFCOrder record) {
        BEGIN();
        UPDATE("TFC_ORDER");
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{userId,jdbcType=BIGINT}");
        }
        
        if (record.getOrderStatus() != null) {
            SET("ORDER_STATUS = #{orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getItemId() != null) {
            SET("ITEM_ID = #{itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinNum() != null) {
            SET("COIN_NUM = #{coinNum,jdbcType=BIGINT}");
        }
        
        if (record.getStorageTime() != null) {
            SET("STORAGE_TIME = #{storageTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHandleTime() != null) {
            SET("HANDLE_TIME = #{handleTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("ORDER_ID = #{orderId,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    protected void applyWhere(TFCOrderExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}