package onight.tfg.ordbgens.tfc.mapper;

import java.util.List;
import onight.tfg.ordbgens.tfc.entity.TFCOrder;
import onight.tfg.ordbgens.tfc.entity.TFCOrderExample;
import onight.tfg.ordbgens.tfc.entity.TFCOrderKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFCOrderMapper extends StaticTableDaoSupport<TFCOrder, TFCOrderExample, TFCOrderKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @SelectProvider(type=TFCOrderSqlProvider.class, method="countByExample")
    int countByExample(TFCOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @DeleteProvider(type=TFCOrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(TFCOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Delete({
        "delete from TFC_ORDER",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFCOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Insert({
        "insert into TFC_ORDER (ORDER_ID, USER_ID, ",
        "ORDER_STATUS, ITEM_ID, ",
        "COIN_NUM, STORAGE_TIME, ",
        "HANDLE_TIME)",
        "values (#{orderId,jdbcType=VARCHAR}, #{userId,jdbcType=BIGINT}, ",
        "#{orderStatus,jdbcType=INTEGER}, #{itemId,jdbcType=VARCHAR}, ",
        "#{coinNum,jdbcType=BIGINT}, #{storageTime,jdbcType=TIMESTAMP}, ",
        "#{handleTime,jdbcType=TIMESTAMP})"
    })
    int insert(TFCOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @InsertProvider(type=TFCOrderSqlProvider.class, method="insertSelective")
    int insertSelective(TFCOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @SelectProvider(type=TFCOrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="ORDER_STATUS", property="orderStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="ITEM_ID", property="itemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="COIN_NUM", property="coinNum", jdbcType=JdbcType.BIGINT),
        @Result(column="STORAGE_TIME", property="storageTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HANDLE_TIME", property="handleTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TFCOrder> selectByExample(TFCOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Select({
        "select",
        "ORDER_ID, USER_ID, ORDER_STATUS, ITEM_ID, COIN_NUM, STORAGE_TIME, HANDLE_TIME",
        "from TFC_ORDER",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="ORDER_STATUS", property="orderStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="ITEM_ID", property="itemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="COIN_NUM", property="coinNum", jdbcType=JdbcType.BIGINT),
        @Result(column="STORAGE_TIME", property="storageTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HANDLE_TIME", property="handleTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TFCOrder selectByPrimaryKey(TFCOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @UpdateProvider(type=TFCOrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TFCOrder record, @Param("example") TFCOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @UpdateProvider(type=TFCOrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TFCOrder record, @Param("example") TFCOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @UpdateProvider(type=TFCOrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFCOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_ORDER
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Update({
        "update TFC_ORDER",
        "set USER_ID = #{userId,jdbcType=BIGINT},",
          "ORDER_STATUS = #{orderStatus,jdbcType=INTEGER},",
          "ITEM_ID = #{itemId,jdbcType=VARCHAR},",
          "COIN_NUM = #{coinNum,jdbcType=BIGINT},",
          "STORAGE_TIME = #{storageTime,jdbcType=TIMESTAMP},",
          "HANDLE_TIME = #{handleTime,jdbcType=TIMESTAMP}",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFCOrder record);
}