package onight.act.ordbgens.act.mapper;

import java.util.List;
import onight.act.ordbgens.act.entity.TActLogs;
import onight.act.ordbgens.act.entity.TActLogsExample;
import onight.act.ordbgens.act.entity.TActLogsKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TActLogsMapper extends StaticTableDaoSupport<TActLogs, TActLogsExample, TActLogsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @SelectProvider(type=TActLogsSqlProvider.class, method="countByExample")
    int countByExample(TActLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @DeleteProvider(type=TActLogsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TActLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Delete({
        "delete from T_ACT_LOGS",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TActLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Insert({
        "insert into T_ACT_LOGS (UUID, SETT_DATE, ",
        "CONS_DATE, TX_SNO, ",
        "SEND_MCHNT_ID, MSG_TYPE, ",
        "ACT_NO, BIZ_TYPE, ",
        "BIZ_DTL_TYPE, DEBT_CUST_ID, ",
        "CRDT_CUST_ID, DC_TYPE, ",
        "AMT, ACT_BAL_AFTER, ",
        "ACT_BAL_BEFORE, UPDT_TIME)",
        "values (#{uuid,jdbcType=VARCHAR}, #{settDate,jdbcType=VARCHAR}, ",
        "#{consDate,jdbcType=VARCHAR}, #{txSno,jdbcType=VARCHAR}, ",
        "#{sendMchntId,jdbcType=VARCHAR}, #{msgType,jdbcType=VARCHAR}, ",
        "#{actNo,jdbcType=VARCHAR}, #{bizType,jdbcType=VARCHAR}, ",
        "#{bizDtlType,jdbcType=VARCHAR}, #{debtCustId,jdbcType=VARCHAR}, ",
        "#{crdtCustId,jdbcType=VARCHAR}, #{dcType,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=DECIMAL}, #{actBalAfter,jdbcType=DECIMAL}, ",
        "#{actBalBefore,jdbcType=DECIMAL}, #{updtTime,jdbcType=TIMESTAMP})"
    })
    int insert(TActLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @InsertProvider(type=TActLogsSqlProvider.class, method="insertSelective")
    int insertSelective(TActLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @SelectProvider(type=TActLogsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SETT_DATE", property="settDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONS_DATE", property="consDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_SNO", property="txSno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_MCHNT_ID", property="sendMchntId", jdbcType=JdbcType.VARCHAR),
        @Result(column="MSG_TYPE", property="msgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_NO", property="actNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_TYPE", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_DTL_TYPE", property="bizDtlType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEBT_CUST_ID", property="debtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRDT_CUST_ID", property="crdtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DC_TYPE", property="dcType", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_AFTER", property="actBalAfter", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_BEFORE", property="actBalBefore", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDT_TIME", property="updtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TActLogs> selectByExample(TActLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Select({
        "select",
        "UUID, SETT_DATE, CONS_DATE, TX_SNO, SEND_MCHNT_ID, MSG_TYPE, ACT_NO, BIZ_TYPE, ",
        "BIZ_DTL_TYPE, DEBT_CUST_ID, CRDT_CUST_ID, DC_TYPE, AMT, ACT_BAL_AFTER, ACT_BAL_BEFORE, ",
        "UPDT_TIME",
        "from T_ACT_LOGS",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SETT_DATE", property="settDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONS_DATE", property="consDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_SNO", property="txSno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_MCHNT_ID", property="sendMchntId", jdbcType=JdbcType.VARCHAR),
        @Result(column="MSG_TYPE", property="msgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_NO", property="actNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_TYPE", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_DTL_TYPE", property="bizDtlType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEBT_CUST_ID", property="debtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRDT_CUST_ID", property="crdtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DC_TYPE", property="dcType", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_AFTER", property="actBalAfter", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_BEFORE", property="actBalBefore", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDT_TIME", property="updtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TActLogs selectByPrimaryKey(TActLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActLogsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TActLogs record, @Param("example") TActLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActLogsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TActLogs record, @Param("example") TActLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActLogsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TActLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Update({
        "update T_ACT_LOGS",
        "set SETT_DATE = #{settDate,jdbcType=VARCHAR},",
          "CONS_DATE = #{consDate,jdbcType=VARCHAR},",
          "TX_SNO = #{txSno,jdbcType=VARCHAR},",
          "SEND_MCHNT_ID = #{sendMchntId,jdbcType=VARCHAR},",
          "MSG_TYPE = #{msgType,jdbcType=VARCHAR},",
          "ACT_NO = #{actNo,jdbcType=VARCHAR},",
          "BIZ_TYPE = #{bizType,jdbcType=VARCHAR},",
          "BIZ_DTL_TYPE = #{bizDtlType,jdbcType=VARCHAR},",
          "DEBT_CUST_ID = #{debtCustId,jdbcType=VARCHAR},",
          "CRDT_CUST_ID = #{crdtCustId,jdbcType=VARCHAR},",
          "DC_TYPE = #{dcType,jdbcType=VARCHAR},",
          "AMT = #{amt,jdbcType=DECIMAL},",
          "ACT_BAL_AFTER = #{actBalAfter,jdbcType=DECIMAL},",
          "ACT_BAL_BEFORE = #{actBalBefore,jdbcType=DECIMAL},",
          "UPDT_TIME = #{updtTime,jdbcType=TIMESTAMP}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TActLogs record);
}