package onight.act.ordbgens.act.mapper;

import java.util.List;
import onight.act.ordbgens.act.entity.TActTradeLogs;
import onight.act.ordbgens.act.entity.TActTradeLogsExample;
import onight.act.ordbgens.act.entity.TActTradeLogsKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TActTradeLogsMapper extends StaticTableDaoSupport<TActTradeLogs, TActTradeLogsExample, TActTradeLogsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @SelectProvider(type=TActTradeLogsSqlProvider.class, method="countByExample")
    int countByExample(TActTradeLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @DeleteProvider(type=TActTradeLogsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TActTradeLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Delete({
        "delete from T_ACT_TRADE_LOGS",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TActTradeLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Insert({
        "insert into T_ACT_TRADE_LOGS (LOG_UUID, SETT_DATE, ",
        "CONS_DATE, TX_SNO, ",
        "SEND_MCHNT_ID, TRANS_CODE, ",
        "SUB_TRANS_CODE, FUND_NO, ",
        "ACT_NO, BIZ_TYPE, ",
        "BIZ_DTL_TYPE, DEBT_CUST_ID, ",
        "CRDT_CUST_ID, DC_TYPE, ",
        "AMT, CNT, FLAG_CANCEL, ",
        "RELATED_TRANS_ID, STATUS, ",
        "ACT_BAL_AFTER, ACT_BAL_BEFORE, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{logUuid,jdbcType=VARCHAR}, #{settDate,jdbcType=VARCHAR}, ",
        "#{consDate,jdbcType=VARCHAR}, #{txSno,jdbcType=VARCHAR}, ",
        "#{sendMchntId,jdbcType=VARCHAR}, #{transCode,jdbcType=VARCHAR}, ",
        "#{subTransCode,jdbcType=VARCHAR}, #{fundNo,jdbcType=VARCHAR}, ",
        "#{actNo,jdbcType=VARCHAR}, #{bizType,jdbcType=VARCHAR}, ",
        "#{bizDtlType,jdbcType=VARCHAR}, #{debtCustId,jdbcType=VARCHAR}, ",
        "#{crdtCustId,jdbcType=VARCHAR}, #{dcType,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=DECIMAL}, #{cnt,jdbcType=INTEGER}, #{flagCancel,jdbcType=CHAR}, ",
        "#{relatedTransId,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{actBalAfter,jdbcType=DECIMAL}, #{actBalBefore,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(TActTradeLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @InsertProvider(type=TActTradeLogsSqlProvider.class, method="insertSelective")
    int insertSelective(TActTradeLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @SelectProvider(type=TActTradeLogsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SETT_DATE", property="settDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONS_DATE", property="consDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_SNO", property="txSno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_MCHNT_ID", property="sendMchntId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANS_CODE", property="transCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SUB_TRANS_CODE", property="subTransCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FUND_NO", property="fundNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_NO", property="actNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_TYPE", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_DTL_TYPE", property="bizDtlType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEBT_CUST_ID", property="debtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRDT_CUST_ID", property="crdtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DC_TYPE", property="dcType", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CNT", property="cnt", jdbcType=JdbcType.INTEGER),
        @Result(column="FLAG_CANCEL", property="flagCancel", jdbcType=JdbcType.CHAR),
        @Result(column="RELATED_TRANS_ID", property="relatedTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_BAL_AFTER", property="actBalAfter", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_BEFORE", property="actBalBefore", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TActTradeLogs> selectByExample(TActTradeLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Select({
        "select",
        "LOG_UUID, SETT_DATE, CONS_DATE, TX_SNO, SEND_MCHNT_ID, TRANS_CODE, SUB_TRANS_CODE, ",
        "FUND_NO, ACT_NO, BIZ_TYPE, BIZ_DTL_TYPE, DEBT_CUST_ID, CRDT_CUST_ID, DC_TYPE, ",
        "AMT, CNT, FLAG_CANCEL, RELATED_TRANS_ID, STATUS, ACT_BAL_AFTER, ACT_BAL_BEFORE, ",
        "CREATE_TIME, UPDATE_TIME",
        "from T_ACT_TRADE_LOGS",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SETT_DATE", property="settDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONS_DATE", property="consDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_SNO", property="txSno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_MCHNT_ID", property="sendMchntId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANS_CODE", property="transCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SUB_TRANS_CODE", property="subTransCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FUND_NO", property="fundNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_NO", property="actNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_TYPE", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIZ_DTL_TYPE", property="bizDtlType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEBT_CUST_ID", property="debtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRDT_CUST_ID", property="crdtCustId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DC_TYPE", property="dcType", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CNT", property="cnt", jdbcType=JdbcType.INTEGER),
        @Result(column="FLAG_CANCEL", property="flagCancel", jdbcType=JdbcType.CHAR),
        @Result(column="RELATED_TRANS_ID", property="relatedTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_BAL_AFTER", property="actBalAfter", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACT_BAL_BEFORE", property="actBalBefore", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TActTradeLogs selectByPrimaryKey(TActTradeLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActTradeLogsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TActTradeLogs record, @Param("example") TActTradeLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActTradeLogsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TActTradeLogs record, @Param("example") TActTradeLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @UpdateProvider(type=TActTradeLogsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TActTradeLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_TRADE_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Update({
        "update T_ACT_TRADE_LOGS",
        "set SETT_DATE = #{settDate,jdbcType=VARCHAR},",
          "CONS_DATE = #{consDate,jdbcType=VARCHAR},",
          "TX_SNO = #{txSno,jdbcType=VARCHAR},",
          "SEND_MCHNT_ID = #{sendMchntId,jdbcType=VARCHAR},",
          "TRANS_CODE = #{transCode,jdbcType=VARCHAR},",
          "SUB_TRANS_CODE = #{subTransCode,jdbcType=VARCHAR},",
          "FUND_NO = #{fundNo,jdbcType=VARCHAR},",
          "ACT_NO = #{actNo,jdbcType=VARCHAR},",
          "BIZ_TYPE = #{bizType,jdbcType=VARCHAR},",
          "BIZ_DTL_TYPE = #{bizDtlType,jdbcType=VARCHAR},",
          "DEBT_CUST_ID = #{debtCustId,jdbcType=VARCHAR},",
          "CRDT_CUST_ID = #{crdtCustId,jdbcType=VARCHAR},",
          "DC_TYPE = #{dcType,jdbcType=VARCHAR},",
          "AMT = #{amt,jdbcType=DECIMAL},",
          "CNT = #{cnt,jdbcType=INTEGER},",
          "FLAG_CANCEL = #{flagCancel,jdbcType=CHAR},",
          "RELATED_TRANS_ID = #{relatedTransId,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=VARCHAR},",
          "ACT_BAL_AFTER = #{actBalAfter,jdbcType=DECIMAL},",
          "ACT_BAL_BEFORE = #{actBalBefore,jdbcType=DECIMAL},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TActTradeLogs record);
}