package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class TActLogsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public TActLogsExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andSettDateIsNull() {
            addCriterion("SETT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSettDateIsNotNull() {
            addCriterion("SETT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettDateEqualTo(String value) {
            addCriterion("SETT_DATE =", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotEqualTo(String value) {
            addCriterion("SETT_DATE <>", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateGreaterThan(String value) {
            addCriterion("SETT_DATE >", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateGreaterThanOrEqualTo(String value) {
            addCriterion("SETT_DATE >=", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLessThan(String value) {
            addCriterion("SETT_DATE <", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLessThanOrEqualTo(String value) {
            addCriterion("SETT_DATE <=", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateLike(String value) {
            addCriterion("SETT_DATE like", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotLike(String value) {
            addCriterion("SETT_DATE not like", value, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateIn(List<String> values) {
            addCriterion("SETT_DATE in", values, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotIn(List<String> values) {
            addCriterion("SETT_DATE not in", values, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateBetween(String value1, String value2) {
            addCriterion("SETT_DATE between", value1, value2, "settDate");
            return (Criteria) this;
        }

        public Criteria andSettDateNotBetween(String value1, String value2) {
            addCriterion("SETT_DATE not between", value1, value2, "settDate");
            return (Criteria) this;
        }

        public Criteria andConsDateIsNull() {
            addCriterion("CONS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andConsDateIsNotNull() {
            addCriterion("CONS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andConsDateEqualTo(String value) {
            addCriterion("CONS_DATE =", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotEqualTo(String value) {
            addCriterion("CONS_DATE <>", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateGreaterThan(String value) {
            addCriterion("CONS_DATE >", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_DATE >=", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLessThan(String value) {
            addCriterion("CONS_DATE <", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLessThanOrEqualTo(String value) {
            addCriterion("CONS_DATE <=", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLike(String value) {
            addCriterion("CONS_DATE like", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotLike(String value) {
            addCriterion("CONS_DATE not like", value, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateIn(List<String> values) {
            addCriterion("CONS_DATE in", values, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotIn(List<String> values) {
            addCriterion("CONS_DATE not in", values, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateBetween(String value1, String value2) {
            addCriterion("CONS_DATE between", value1, value2, "consDate");
            return (Criteria) this;
        }

        public Criteria andConsDateNotBetween(String value1, String value2) {
            addCriterion("CONS_DATE not between", value1, value2, "consDate");
            return (Criteria) this;
        }

        public Criteria andTxSnoIsNull() {
            addCriterion("TX_SNO is null");
            return (Criteria) this;
        }

        public Criteria andTxSnoIsNotNull() {
            addCriterion("TX_SNO is not null");
            return (Criteria) this;
        }

        public Criteria andTxSnoEqualTo(String value) {
            addCriterion("TX_SNO =", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotEqualTo(String value) {
            addCriterion("TX_SNO <>", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoGreaterThan(String value) {
            addCriterion("TX_SNO >", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoGreaterThanOrEqualTo(String value) {
            addCriterion("TX_SNO >=", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLessThan(String value) {
            addCriterion("TX_SNO <", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLessThanOrEqualTo(String value) {
            addCriterion("TX_SNO <=", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoLike(String value) {
            addCriterion("TX_SNO like", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotLike(String value) {
            addCriterion("TX_SNO not like", value, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoIn(List<String> values) {
            addCriterion("TX_SNO in", values, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotIn(List<String> values) {
            addCriterion("TX_SNO not in", values, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoBetween(String value1, String value2) {
            addCriterion("TX_SNO between", value1, value2, "txSno");
            return (Criteria) this;
        }

        public Criteria andTxSnoNotBetween(String value1, String value2) {
            addCriterion("TX_SNO not between", value1, value2, "txSno");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdIsNull() {
            addCriterion("SEND_MCHNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdIsNotNull() {
            addCriterion("SEND_MCHNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdEqualTo(String value) {
            addCriterion("SEND_MCHNT_ID =", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdNotEqualTo(String value) {
            addCriterion("SEND_MCHNT_ID <>", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdGreaterThan(String value) {
            addCriterion("SEND_MCHNT_ID >", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_MCHNT_ID >=", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdLessThan(String value) {
            addCriterion("SEND_MCHNT_ID <", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdLessThanOrEqualTo(String value) {
            addCriterion("SEND_MCHNT_ID <=", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdLike(String value) {
            addCriterion("SEND_MCHNT_ID like", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdNotLike(String value) {
            addCriterion("SEND_MCHNT_ID not like", value, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdIn(List<String> values) {
            addCriterion("SEND_MCHNT_ID in", values, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdNotIn(List<String> values) {
            addCriterion("SEND_MCHNT_ID not in", values, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdBetween(String value1, String value2) {
            addCriterion("SEND_MCHNT_ID between", value1, value2, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdNotBetween(String value1, String value2) {
            addCriterion("SEND_MCHNT_ID not between", value1, value2, "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNull() {
            addCriterion("MSG_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNotNull() {
            addCriterion("MSG_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeEqualTo(String value) {
            addCriterion("MSG_TYPE =", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotEqualTo(String value) {
            addCriterion("MSG_TYPE <>", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThan(String value) {
            addCriterion("MSG_TYPE >", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE >=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThan(String value) {
            addCriterion("MSG_TYPE <", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE <=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLike(String value) {
            addCriterion("MSG_TYPE like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotLike(String value) {
            addCriterion("MSG_TYPE not like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIn(List<String> values) {
            addCriterion("MSG_TYPE in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotIn(List<String> values) {
            addCriterion("MSG_TYPE not in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeBetween(String value1, String value2) {
            addCriterion("MSG_TYPE between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotBetween(String value1, String value2) {
            addCriterion("MSG_TYPE not between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andActNoIsNull() {
            addCriterion("ACT_NO is null");
            return (Criteria) this;
        }

        public Criteria andActNoIsNotNull() {
            addCriterion("ACT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andActNoEqualTo(String value) {
            addCriterion("ACT_NO =", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotEqualTo(String value) {
            addCriterion("ACT_NO <>", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThan(String value) {
            addCriterion("ACT_NO >", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_NO >=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThan(String value) {
            addCriterion("ACT_NO <", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThanOrEqualTo(String value) {
            addCriterion("ACT_NO <=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLike(String value) {
            addCriterion("ACT_NO like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotLike(String value) {
            addCriterion("ACT_NO not like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoIn(List<String> values) {
            addCriterion("ACT_NO in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotIn(List<String> values) {
            addCriterion("ACT_NO not in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoBetween(String value1, String value2) {
            addCriterion("ACT_NO between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotBetween(String value1, String value2) {
            addCriterion("ACT_NO not between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("BIZ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("BIZ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("BIZ_TYPE =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("BIZ_TYPE <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("BIZ_TYPE >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("BIZ_TYPE <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("BIZ_TYPE like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("BIZ_TYPE not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("BIZ_TYPE in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("BIZ_TYPE not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIsNull() {
            addCriterion("BIZ_DTL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIsNotNull() {
            addCriterion("BIZ_DTL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE =", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE <>", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeGreaterThan(String value) {
            addCriterion("BIZ_DTL_TYPE >", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE >=", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLessThan(String value) {
            addCriterion("BIZ_DTL_TYPE <", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLessThanOrEqualTo(String value) {
            addCriterion("BIZ_DTL_TYPE <=", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLike(String value) {
            addCriterion("BIZ_DTL_TYPE like", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotLike(String value) {
            addCriterion("BIZ_DTL_TYPE not like", value, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeIn(List<String> values) {
            addCriterion("BIZ_DTL_TYPE in", values, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotIn(List<String> values) {
            addCriterion("BIZ_DTL_TYPE not in", values, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeBetween(String value1, String value2) {
            addCriterion("BIZ_DTL_TYPE between", value1, value2, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeNotBetween(String value1, String value2) {
            addCriterion("BIZ_DTL_TYPE not between", value1, value2, "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdIsNull() {
            addCriterion("DEBT_CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdIsNotNull() {
            addCriterion("DEBT_CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdEqualTo(String value) {
            addCriterion("DEBT_CUST_ID =", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdNotEqualTo(String value) {
            addCriterion("DEBT_CUST_ID <>", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdGreaterThan(String value) {
            addCriterion("DEBT_CUST_ID >", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEBT_CUST_ID >=", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdLessThan(String value) {
            addCriterion("DEBT_CUST_ID <", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdLessThanOrEqualTo(String value) {
            addCriterion("DEBT_CUST_ID <=", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdLike(String value) {
            addCriterion("DEBT_CUST_ID like", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdNotLike(String value) {
            addCriterion("DEBT_CUST_ID not like", value, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdIn(List<String> values) {
            addCriterion("DEBT_CUST_ID in", values, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdNotIn(List<String> values) {
            addCriterion("DEBT_CUST_ID not in", values, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdBetween(String value1, String value2) {
            addCriterion("DEBT_CUST_ID between", value1, value2, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdNotBetween(String value1, String value2) {
            addCriterion("DEBT_CUST_ID not between", value1, value2, "debtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdIsNull() {
            addCriterion("CRDT_CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdIsNotNull() {
            addCriterion("CRDT_CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdEqualTo(String value) {
            addCriterion("CRDT_CUST_ID =", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdNotEqualTo(String value) {
            addCriterion("CRDT_CUST_ID <>", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdGreaterThan(String value) {
            addCriterion("CRDT_CUST_ID >", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRDT_CUST_ID >=", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdLessThan(String value) {
            addCriterion("CRDT_CUST_ID <", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdLessThanOrEqualTo(String value) {
            addCriterion("CRDT_CUST_ID <=", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdLike(String value) {
            addCriterion("CRDT_CUST_ID like", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdNotLike(String value) {
            addCriterion("CRDT_CUST_ID not like", value, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdIn(List<String> values) {
            addCriterion("CRDT_CUST_ID in", values, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdNotIn(List<String> values) {
            addCriterion("CRDT_CUST_ID not in", values, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdBetween(String value1, String value2) {
            addCriterion("CRDT_CUST_ID between", value1, value2, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdNotBetween(String value1, String value2) {
            addCriterion("CRDT_CUST_ID not between", value1, value2, "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andDcTypeIsNull() {
            addCriterion("DC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDcTypeIsNotNull() {
            addCriterion("DC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDcTypeEqualTo(String value) {
            addCriterion("DC_TYPE =", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotEqualTo(String value) {
            addCriterion("DC_TYPE <>", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeGreaterThan(String value) {
            addCriterion("DC_TYPE >", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DC_TYPE >=", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLessThan(String value) {
            addCriterion("DC_TYPE <", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLessThanOrEqualTo(String value) {
            addCriterion("DC_TYPE <=", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeLike(String value) {
            addCriterion("DC_TYPE like", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotLike(String value) {
            addCriterion("DC_TYPE not like", value, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeIn(List<String> values) {
            addCriterion("DC_TYPE in", values, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotIn(List<String> values) {
            addCriterion("DC_TYPE not in", values, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeBetween(String value1, String value2) {
            addCriterion("DC_TYPE between", value1, value2, "dcType");
            return (Criteria) this;
        }

        public Criteria andDcTypeNotBetween(String value1, String value2) {
            addCriterion("DC_TYPE not between", value1, value2, "dcType");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIsNull() {
            addCriterion("ACT_BAL_AFTER is null");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIsNotNull() {
            addCriterion("ACT_BAL_AFTER is not null");
            return (Criteria) this;
        }

        public Criteria andActBalAfterEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER =", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <>", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER >", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER >=", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterLessThan(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_AFTER <=", value, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_AFTER in", values, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_AFTER not in", values, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_AFTER between", value1, value2, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_AFTER not between", value1, value2, "actBalAfter");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIsNull() {
            addCriterion("ACT_BAL_BEFORE is null");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIsNotNull() {
            addCriterion("ACT_BAL_BEFORE is not null");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE =", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <>", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE >", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE >=", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeLessThan(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL_BEFORE <=", value, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_BEFORE in", values, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL_BEFORE not in", values, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_BEFORE between", value1, value2, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andActBalBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL_BEFORE not between", value1, value2, "actBalBefore");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeIsNull() {
            addCriterion("UPDT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeIsNotNull() {
            addCriterion("UPDT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeEqualTo(Date value) {
            addCriterion("UPDT_TIME =", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeNotEqualTo(Date value) {
            addCriterion("UPDT_TIME <>", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeGreaterThan(Date value) {
            addCriterion("UPDT_TIME >", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDT_TIME >=", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeLessThan(Date value) {
            addCriterion("UPDT_TIME <", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDT_TIME <=", value, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeIn(List<Date> values) {
            addCriterion("UPDT_TIME in", values, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeNotIn(List<Date> values) {
            addCriterion("UPDT_TIME not in", values, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeBetween(Date value1, Date value2) {
            addCriterion("UPDT_TIME between", value1, value2, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUpdtTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDT_TIME not between", value1, value2, "updtTime");
            return (Criteria) this;
        }

        public Criteria andUuidLikeInsensitive(String value) {
            addCriterion("upper(UUID) like", value.toUpperCase(), "uuid");
            return (Criteria) this;
        }

        public Criteria andSettDateLikeInsensitive(String value) {
            addCriterion("upper(SETT_DATE) like", value.toUpperCase(), "settDate");
            return (Criteria) this;
        }

        public Criteria andConsDateLikeInsensitive(String value) {
            addCriterion("upper(CONS_DATE) like", value.toUpperCase(), "consDate");
            return (Criteria) this;
        }

        public Criteria andTxSnoLikeInsensitive(String value) {
            addCriterion("upper(TX_SNO) like", value.toUpperCase(), "txSno");
            return (Criteria) this;
        }

        public Criteria andSendMchntIdLikeInsensitive(String value) {
            addCriterion("upper(SEND_MCHNT_ID) like", value.toUpperCase(), "sendMchntId");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLikeInsensitive(String value) {
            addCriterion("upper(MSG_TYPE) like", value.toUpperCase(), "msgType");
            return (Criteria) this;
        }

        public Criteria andActNoLikeInsensitive(String value) {
            addCriterion("upper(ACT_NO) like", value.toUpperCase(), "actNo");
            return (Criteria) this;
        }

        public Criteria andBizTypeLikeInsensitive(String value) {
            addCriterion("upper(BIZ_TYPE) like", value.toUpperCase(), "bizType");
            return (Criteria) this;
        }

        public Criteria andBizDtlTypeLikeInsensitive(String value) {
            addCriterion("upper(BIZ_DTL_TYPE) like", value.toUpperCase(), "bizDtlType");
            return (Criteria) this;
        }

        public Criteria andDebtCustIdLikeInsensitive(String value) {
            addCriterion("upper(DEBT_CUST_ID) like", value.toUpperCase(), "debtCustId");
            return (Criteria) this;
        }

        public Criteria andCrdtCustIdLikeInsensitive(String value) {
            addCriterion("upper(CRDT_CUST_ID) like", value.toUpperCase(), "crdtCustId");
            return (Criteria) this;
        }

        public Criteria andDcTypeLikeInsensitive(String value) {
            addCriterion("upper(DC_TYPE) like", value.toUpperCase(), "dcType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 07 11:37:59 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}