package onight.act.ordbgens.act.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="T_ACT_LOGS")
@AllArgsConstructor
@NoArgsConstructor
public class TActLogs extends TActLogsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.SETT_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String settDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.CONS_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String consDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.TX_SNO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String txSno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.SEND_MCHNT_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String sendMchntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.MSG_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.ACT_NO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String actNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.BIZ_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.BIZ_DTL_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String bizDtlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.DEBT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String debtCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.CRDT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String crdtCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.DC_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private String dcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.AMT
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.ACT_BAL_AFTER
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private BigDecimal actBalAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.ACT_BAL_BEFORE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private BigDecimal actBalBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACT_LOGS.UPDT_TIME
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    private Date updtTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.SETT_DATE
     *
     * @return the value of T_ACT_LOGS.SETT_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getSettDate() {
        return settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.SETT_DATE
     *
     * @param settDate the value for T_ACT_LOGS.SETT_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setSettDate(String settDate) {
        this.settDate = settDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.CONS_DATE
     *
     * @return the value of T_ACT_LOGS.CONS_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getConsDate() {
        return consDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.CONS_DATE
     *
     * @param consDate the value for T_ACT_LOGS.CONS_DATE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setConsDate(String consDate) {
        this.consDate = consDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.TX_SNO
     *
     * @return the value of T_ACT_LOGS.TX_SNO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getTxSno() {
        return txSno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.TX_SNO
     *
     * @param txSno the value for T_ACT_LOGS.TX_SNO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setTxSno(String txSno) {
        this.txSno = txSno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.SEND_MCHNT_ID
     *
     * @return the value of T_ACT_LOGS.SEND_MCHNT_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getSendMchntId() {
        return sendMchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.SEND_MCHNT_ID
     *
     * @param sendMchntId the value for T_ACT_LOGS.SEND_MCHNT_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setSendMchntId(String sendMchntId) {
        this.sendMchntId = sendMchntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.MSG_TYPE
     *
     * @return the value of T_ACT_LOGS.MSG_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.MSG_TYPE
     *
     * @param msgType the value for T_ACT_LOGS.MSG_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.ACT_NO
     *
     * @return the value of T_ACT_LOGS.ACT_NO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getActNo() {
        return actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.ACT_NO
     *
     * @param actNo the value for T_ACT_LOGS.ACT_NO
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setActNo(String actNo) {
        this.actNo = actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.BIZ_TYPE
     *
     * @return the value of T_ACT_LOGS.BIZ_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.BIZ_TYPE
     *
     * @param bizType the value for T_ACT_LOGS.BIZ_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.BIZ_DTL_TYPE
     *
     * @return the value of T_ACT_LOGS.BIZ_DTL_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getBizDtlType() {
        return bizDtlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.BIZ_DTL_TYPE
     *
     * @param bizDtlType the value for T_ACT_LOGS.BIZ_DTL_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setBizDtlType(String bizDtlType) {
        this.bizDtlType = bizDtlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.DEBT_CUST_ID
     *
     * @return the value of T_ACT_LOGS.DEBT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getDebtCustId() {
        return debtCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.DEBT_CUST_ID
     *
     * @param debtCustId the value for T_ACT_LOGS.DEBT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setDebtCustId(String debtCustId) {
        this.debtCustId = debtCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.CRDT_CUST_ID
     *
     * @return the value of T_ACT_LOGS.CRDT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getCrdtCustId() {
        return crdtCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.CRDT_CUST_ID
     *
     * @param crdtCustId the value for T_ACT_LOGS.CRDT_CUST_ID
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setCrdtCustId(String crdtCustId) {
        this.crdtCustId = crdtCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.DC_TYPE
     *
     * @return the value of T_ACT_LOGS.DC_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public String getDcType() {
        return dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.DC_TYPE
     *
     * @param dcType the value for T_ACT_LOGS.DC_TYPE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setDcType(String dcType) {
        this.dcType = dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.AMT
     *
     * @return the value of T_ACT_LOGS.AMT
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.AMT
     *
     * @param amt the value for T_ACT_LOGS.AMT
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.ACT_BAL_AFTER
     *
     * @return the value of T_ACT_LOGS.ACT_BAL_AFTER
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public BigDecimal getActBalAfter() {
        return actBalAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.ACT_BAL_AFTER
     *
     * @param actBalAfter the value for T_ACT_LOGS.ACT_BAL_AFTER
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setActBalAfter(BigDecimal actBalAfter) {
        this.actBalAfter = actBalAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.ACT_BAL_BEFORE
     *
     * @return the value of T_ACT_LOGS.ACT_BAL_BEFORE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public BigDecimal getActBalBefore() {
        return actBalBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.ACT_BAL_BEFORE
     *
     * @param actBalBefore the value for T_ACT_LOGS.ACT_BAL_BEFORE
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setActBalBefore(BigDecimal actBalBefore) {
        this.actBalBefore = actBalBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACT_LOGS.UPDT_TIME
     *
     * @return the value of T_ACT_LOGS.UPDT_TIME
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public Date getUpdtTime() {
        return updtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACT_LOGS.UPDT_TIME
     *
     * @param updtTime the value for T_ACT_LOGS.UPDT_TIME
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    public void setUpdtTime(Date updtTime) {
        this.updtTime = updtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TActLogs other = (TActLogs) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getSettDate() == null ? other.getSettDate() == null : this.getSettDate().equals(other.getSettDate()))
            && (this.getConsDate() == null ? other.getConsDate() == null : this.getConsDate().equals(other.getConsDate()))
            && (this.getTxSno() == null ? other.getTxSno() == null : this.getTxSno().equals(other.getTxSno()))
            && (this.getSendMchntId() == null ? other.getSendMchntId() == null : this.getSendMchntId().equals(other.getSendMchntId()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getActNo() == null ? other.getActNo() == null : this.getActNo().equals(other.getActNo()))
            && (this.getBizType() == null ? other.getBizType() == null : this.getBizType().equals(other.getBizType()))
            && (this.getBizDtlType() == null ? other.getBizDtlType() == null : this.getBizDtlType().equals(other.getBizDtlType()))
            && (this.getDebtCustId() == null ? other.getDebtCustId() == null : this.getDebtCustId().equals(other.getDebtCustId()))
            && (this.getCrdtCustId() == null ? other.getCrdtCustId() == null : this.getCrdtCustId().equals(other.getCrdtCustId()))
            && (this.getDcType() == null ? other.getDcType() == null : this.getDcType().equals(other.getDcType()))
            && (this.getAmt() == null ? other.getAmt() == null : this.getAmt().equals(other.getAmt()))
            && (this.getActBalAfter() == null ? other.getActBalAfter() == null : this.getActBalAfter().equals(other.getActBalAfter()))
            && (this.getActBalBefore() == null ? other.getActBalBefore() == null : this.getActBalBefore().equals(other.getActBalBefore()))
            && (this.getUpdtTime() == null ? other.getUpdtTime() == null : this.getUpdtTime().equals(other.getUpdtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getSettDate() == null) ? 0 : getSettDate().hashCode());
        result = prime * result + ((getConsDate() == null) ? 0 : getConsDate().hashCode());
        result = prime * result + ((getTxSno() == null) ? 0 : getTxSno().hashCode());
        result = prime * result + ((getSendMchntId() == null) ? 0 : getSendMchntId().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getActNo() == null) ? 0 : getActNo().hashCode());
        result = prime * result + ((getBizType() == null) ? 0 : getBizType().hashCode());
        result = prime * result + ((getBizDtlType() == null) ? 0 : getBizDtlType().hashCode());
        result = prime * result + ((getDebtCustId() == null) ? 0 : getDebtCustId().hashCode());
        result = prime * result + ((getCrdtCustId() == null) ? 0 : getCrdtCustId().hashCode());
        result = prime * result + ((getDcType() == null) ? 0 : getDcType().hashCode());
        result = prime * result + ((getAmt() == null) ? 0 : getAmt().hashCode());
        result = prime * result + ((getActBalAfter() == null) ? 0 : getActBalAfter().hashCode());
        result = prime * result + ((getActBalBefore() == null) ? 0 : getActBalBefore().hashCode());
        result = prime * result + ((getUpdtTime() == null) ? 0 : getUpdtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACT_LOGS
     *
     * @mbggenerated Mon Dec 07 11:37:59 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settDate=").append(settDate);
        sb.append(", consDate=").append(consDate);
        sb.append(", txSno=").append(txSno);
        sb.append(", sendMchntId=").append(sendMchntId);
        sb.append(", msgType=").append(msgType);
        sb.append(", actNo=").append(actNo);
        sb.append(", bizType=").append(bizType);
        sb.append(", bizDtlType=").append(bizDtlType);
        sb.append(", debtCustId=").append(debtCustId);
        sb.append(", crdtCustId=").append(crdtCustId);
        sb.append(", dcType=").append(dcType);
        sb.append(", amt=").append(amt);
        sb.append(", actBalAfter=").append(actBalAfter);
        sb.append(", actBalBefore=").append(actBalBefore);
        sb.append(", updtTime=").append(updtTime);
        sb.append("]");
        return sb.toString();
    }
}