package onight.tfg.ordbgens.sys.mapper;

import java.util.List;
import onight.tfg.ordbgens.sys.entity.TSysOpLogs;
import onight.tfg.ordbgens.sys.entity.TSysOpLogsExample;
import onight.tfg.ordbgens.sys.entity.TSysOpLogsKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TSysOpLogsMapper extends StaticTableDaoSupport<TSysOpLogs, TSysOpLogsExample, TSysOpLogsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @SelectProvider(type=TSysOpLogsSqlProvider.class, method="countByExample")
    int countByExample(TSysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @DeleteProvider(type=TSysOpLogsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TSysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Delete({
        "delete from T_SYS_OP_LOGS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TSysOpLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Insert({
        "insert into T_SYS_OP_LOGS (ID, SKEYS, ",
        "CONTENTS, LEVEL, ",
        "CRT_TIME)",
        "values (#{id,jdbcType=VARCHAR}, #{skeys,jdbcType=VARCHAR}, ",
        "#{contents,jdbcType=VARCHAR}, #{level,jdbcType=VARCHAR}, ",
        "#{crtTime,jdbcType=TIMESTAMP})"
    })
    int insert(TSysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @InsertProvider(type=TSysOpLogsSqlProvider.class, method="insertSelective")
    int insertSelective(TSysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @SelectProvider(type=TSysOpLogsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SKEYS", property="skeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENTS", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVEL", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRT_TIME", property="crtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TSysOpLogs> selectByExample(TSysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Select({
        "select",
        "ID, SKEYS, CONTENTS, LEVEL, CRT_TIME",
        "from T_SYS_OP_LOGS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SKEYS", property="skeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENTS", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVEL", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRT_TIME", property="crtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TSysOpLogs selectByPrimaryKey(TSysOpLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysOpLogsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TSysOpLogs record, @Param("example") TSysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysOpLogsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TSysOpLogs record, @Param("example") TSysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysOpLogsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TSysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Update({
        "update T_SYS_OP_LOGS",
        "set SKEYS = #{skeys,jdbcType=VARCHAR},",
          "CONTENTS = #{contents,jdbcType=VARCHAR},",
          "LEVEL = #{level,jdbcType=VARCHAR},",
          "CRT_TIME = #{crtTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TSysOpLogs record);
}