package onight.tfg.ordbgens.sys.mapper;

import java.util.List;
import onight.tfg.ordbgens.sys.entity.TSysBusiness;
import onight.tfg.ordbgens.sys.entity.TSysBusinessExample;
import onight.tfg.ordbgens.sys.entity.TSysBusinessKey;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TSysBusinessMapper extends StaticTableDaoSupport<TSysBusiness, TSysBusinessExample, TSysBusinessKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @SelectProvider(type=TSysBusinessSqlProvider.class, method="countByExample")
    int countByExample(TSysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @DeleteProvider(type=TSysBusinessSqlProvider.class, method="deleteByExample")
    int deleteByExample(TSysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Delete({
        "delete from T_SYS_BUSINESS",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TSysBusinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Insert({
        "insert into T_SYS_BUSINESS (BUSINESS_ID, BUSINESS_NAME, ",
        "BUSINESS_DESC, BUSINESS_MANAGER, ",
        "BUSINESS_MOBILE, BUSINESS_SEQ, ",
        "BEGIN_TIME, END_TIME, ",
        "STATUS, BUSINESS_DATA_PERMISSION)",
        "values (#{businessId,jdbcType=VARCHAR}, #{businessName,jdbcType=VARCHAR}, ",
        "#{businessDesc,jdbcType=VARCHAR}, #{businessManager,jdbcType=VARCHAR}, ",
        "#{businessMobile,jdbcType=VARCHAR}, #{businessSeq,jdbcType=INTEGER}, ",
        "#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER}, #{businessDataPermission,jdbcType=INTEGER})"
    })
    int insert(TSysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @InsertProvider(type=TSysBusinessSqlProvider.class, method="insertSelective")
    int insertSelective(TSysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @SelectProvider(type=TSysBusinessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="BUSINESS_ID", property="businessId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUSINESS_NAME", property="businessName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_DESC", property="businessDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MANAGER", property="businessManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MOBILE", property="businessMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_SEQ", property="businessSeq", jdbcType=JdbcType.INTEGER),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="BUSINESS_DATA_PERMISSION", property="businessDataPermission", jdbcType=JdbcType.INTEGER)
    })
    List<TSysBusiness> selectByExample(TSysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Select({
        "select",
        "BUSINESS_ID, BUSINESS_NAME, BUSINESS_DESC, BUSINESS_MANAGER, BUSINESS_MOBILE, ",
        "BUSINESS_SEQ, BEGIN_TIME, END_TIME, STATUS, BUSINESS_DATA_PERMISSION",
        "from T_SYS_BUSINESS",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="BUSINESS_ID", property="businessId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUSINESS_NAME", property="businessName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_DESC", property="businessDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MANAGER", property="businessManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MOBILE", property="businessMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_SEQ", property="businessSeq", jdbcType=JdbcType.INTEGER),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="BUSINESS_DATA_PERMISSION", property="businessDataPermission", jdbcType=JdbcType.INTEGER)
    })
    TSysBusiness selectByPrimaryKey(TSysBusinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysBusinessSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TSysBusiness record, @Param("example") TSysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysBusinessSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TSysBusiness record, @Param("example") TSysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @UpdateProvider(type=TSysBusinessSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TSysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Wed Dec 16 19:48:41 CST 2015
     */
    @Update({
        "update T_SYS_BUSINESS",
        "set BUSINESS_NAME = #{businessName,jdbcType=VARCHAR},",
          "BUSINESS_DESC = #{businessDesc,jdbcType=VARCHAR},",
          "BUSINESS_MANAGER = #{businessManager,jdbcType=VARCHAR},",
          "BUSINESS_MOBILE = #{businessMobile,jdbcType=VARCHAR},",
          "BUSINESS_SEQ = #{businessSeq,jdbcType=INTEGER},",
          "BEGIN_TIME = #{beginTime,jdbcType=TIMESTAMP},",
          "END_TIME = #{endTime,jdbcType=TIMESTAMP},",
          "STATUS = #{status,jdbcType=INTEGER},",
          "BUSINESS_DATA_PERMISSION = #{businessDataPermission,jdbcType=INTEGER}",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TSysBusiness record);
}