package onight.tfg.ordbgens.tfc.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class TFCConfigUpdateLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFC_CONFIG_UPDATE_LOG.CONFIG_TYPE
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    private String configType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFC_CONFIG_UPDATE_LOG.CONFIG_TYPE
     *
     * @return the value of TFC_CONFIG_UPDATE_LOG.CONFIG_TYPE
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFC_CONFIG_UPDATE_LOG.CONFIG_TYPE
     *
     * @param configType the value for TFC_CONFIG_UPDATE_LOG.CONFIG_TYPE
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    public void setConfigType(String configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_CONFIG_UPDATE_LOG
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TFCConfigUpdateLogKey other = (TFCConfigUpdateLogKey) that;
        return (this.getConfigType() == null ? other.getConfigType() == null : this.getConfigType().equals(other.getConfigType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_CONFIG_UPDATE_LOG
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getConfigType() == null) ? 0 : getConfigType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFC_CONFIG_UPDATE_LOG
     *
     * @mbggenerated Wed Dec 16 19:48:42 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configType=").append(configType);
        sb.append("]");
        return sb.toString();
    }
}