package onight.zjfae.ordbgens.app.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_CACHE_ITEMS")
@AllArgsConstructor
@NoArgsConstructor
public class APPCacheItems extends APPCacheItemsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.CACHE_KEY
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private String cacheKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.CATALOGS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private String catalogs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.CONTENTS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.STR_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private String strV1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.STR_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private String strV2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.FLOAT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private BigDecimal floatV1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.FLOAT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private BigDecimal floatV2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.INT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Long intV1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.INT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Long intV2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.DT_V3
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Date dtV3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.DT_V4
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Date dtV4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.CRT_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.UPD_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.TTL
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Integer ttl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CACHE_ITEMS.STATUS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.CACHE_KEY
     *
     * @return the value of APP_CACHE_ITEMS.CACHE_KEY
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public String getCacheKey() {
        return cacheKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.CACHE_KEY
     *
     * @param cacheKey the value for APP_CACHE_ITEMS.CACHE_KEY
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setCacheKey(String cacheKey) {
        this.cacheKey = cacheKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.CATALOGS
     *
     * @return the value of APP_CACHE_ITEMS.CATALOGS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public String getCatalogs() {
        return catalogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.CATALOGS
     *
     * @param catalogs the value for APP_CACHE_ITEMS.CATALOGS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setCatalogs(String catalogs) {
        this.catalogs = catalogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.CONTENTS
     *
     * @return the value of APP_CACHE_ITEMS.CONTENTS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.CONTENTS
     *
     * @param contents the value for APP_CACHE_ITEMS.CONTENTS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.STR_V1
     *
     * @return the value of APP_CACHE_ITEMS.STR_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public String getStrV1() {
        return strV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.STR_V1
     *
     * @param strV1 the value for APP_CACHE_ITEMS.STR_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setStrV1(String strV1) {
        this.strV1 = strV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.STR_V2
     *
     * @return the value of APP_CACHE_ITEMS.STR_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public String getStrV2() {
        return strV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.STR_V2
     *
     * @param strV2 the value for APP_CACHE_ITEMS.STR_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setStrV2(String strV2) {
        this.strV2 = strV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.FLOAT_V1
     *
     * @return the value of APP_CACHE_ITEMS.FLOAT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public BigDecimal getFloatV1() {
        return floatV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.FLOAT_V1
     *
     * @param floatV1 the value for APP_CACHE_ITEMS.FLOAT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setFloatV1(BigDecimal floatV1) {
        this.floatV1 = floatV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.FLOAT_V2
     *
     * @return the value of APP_CACHE_ITEMS.FLOAT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public BigDecimal getFloatV2() {
        return floatV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.FLOAT_V2
     *
     * @param floatV2 the value for APP_CACHE_ITEMS.FLOAT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setFloatV2(BigDecimal floatV2) {
        this.floatV2 = floatV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.INT_V1
     *
     * @return the value of APP_CACHE_ITEMS.INT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Long getIntV1() {
        return intV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.INT_V1
     *
     * @param intV1 the value for APP_CACHE_ITEMS.INT_V1
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setIntV1(Long intV1) {
        this.intV1 = intV1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.INT_V2
     *
     * @return the value of APP_CACHE_ITEMS.INT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Long getIntV2() {
        return intV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.INT_V2
     *
     * @param intV2 the value for APP_CACHE_ITEMS.INT_V2
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setIntV2(Long intV2) {
        this.intV2 = intV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.DT_V3
     *
     * @return the value of APP_CACHE_ITEMS.DT_V3
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Date getDtV3() {
        return dtV3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.DT_V3
     *
     * @param dtV3 the value for APP_CACHE_ITEMS.DT_V3
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setDtV3(Date dtV3) {
        this.dtV3 = dtV3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.DT_V4
     *
     * @return the value of APP_CACHE_ITEMS.DT_V4
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Date getDtV4() {
        return dtV4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.DT_V4
     *
     * @param dtV4 the value for APP_CACHE_ITEMS.DT_V4
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setDtV4(Date dtV4) {
        this.dtV4 = dtV4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.CRT_TIME
     *
     * @return the value of APP_CACHE_ITEMS.CRT_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.CRT_TIME
     *
     * @param crtTime the value for APP_CACHE_ITEMS.CRT_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.UPD_TIME
     *
     * @return the value of APP_CACHE_ITEMS.UPD_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.UPD_TIME
     *
     * @param updTime the value for APP_CACHE_ITEMS.UPD_TIME
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.TTL
     *
     * @return the value of APP_CACHE_ITEMS.TTL
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Integer getTtl() {
        return ttl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.TTL
     *
     * @param ttl the value for APP_CACHE_ITEMS.TTL
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CACHE_ITEMS.STATUS
     *
     * @return the value of APP_CACHE_ITEMS.STATUS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CACHE_ITEMS.STATUS
     *
     * @param status the value for APP_CACHE_ITEMS.STATUS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPCacheItems other = (APPCacheItems) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getCacheKey() == null ? other.getCacheKey() == null : this.getCacheKey().equals(other.getCacheKey()))
            && (this.getCatalogs() == null ? other.getCatalogs() == null : this.getCatalogs().equals(other.getCatalogs()))
            && (this.getContents() == null ? other.getContents() == null : this.getContents().equals(other.getContents()))
            && (this.getStrV1() == null ? other.getStrV1() == null : this.getStrV1().equals(other.getStrV1()))
            && (this.getStrV2() == null ? other.getStrV2() == null : this.getStrV2().equals(other.getStrV2()))
            && (this.getFloatV1() == null ? other.getFloatV1() == null : this.getFloatV1().equals(other.getFloatV1()))
            && (this.getFloatV2() == null ? other.getFloatV2() == null : this.getFloatV2().equals(other.getFloatV2()))
            && (this.getIntV1() == null ? other.getIntV1() == null : this.getIntV1().equals(other.getIntV1()))
            && (this.getIntV2() == null ? other.getIntV2() == null : this.getIntV2().equals(other.getIntV2()))
            && (this.getDtV3() == null ? other.getDtV3() == null : this.getDtV3().equals(other.getDtV3()))
            && (this.getDtV4() == null ? other.getDtV4() == null : this.getDtV4().equals(other.getDtV4()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getTtl() == null ? other.getTtl() == null : this.getTtl().equals(other.getTtl()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getCacheKey() == null) ? 0 : getCacheKey().hashCode());
        result = prime * result + ((getCatalogs() == null) ? 0 : getCatalogs().hashCode());
        result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
        result = prime * result + ((getStrV1() == null) ? 0 : getStrV1().hashCode());
        result = prime * result + ((getStrV2() == null) ? 0 : getStrV2().hashCode());
        result = prime * result + ((getFloatV1() == null) ? 0 : getFloatV1().hashCode());
        result = prime * result + ((getFloatV2() == null) ? 0 : getFloatV2().hashCode());
        result = prime * result + ((getIntV1() == null) ? 0 : getIntV1().hashCode());
        result = prime * result + ((getIntV2() == null) ? 0 : getIntV2().hashCode());
        result = prime * result + ((getDtV3() == null) ? 0 : getDtV3().hashCode());
        result = prime * result + ((getDtV4() == null) ? 0 : getDtV4().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getTtl() == null) ? 0 : getTtl().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Mon May 09 10:59:33 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cacheKey=").append(cacheKey);
        sb.append(", catalogs=").append(catalogs);
        sb.append(", contents=").append(contents);
        sb.append(", strV1=").append(strV1);
        sb.append(", strV2=").append(strV2);
        sb.append(", floatV1=").append(floatV1);
        sb.append(", floatV2=").append(floatV2);
        sb.append(", intV1=").append(intV1);
        sb.append(", intV2=").append(intV2);
        sb.append(", dtV3=").append(dtV3);
        sb.append(", dtV4=").append(dtV4);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", ttl=").append(ttl);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}