package onight.zjfae.ordbgens.app.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class APPCacheItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public APPCacheItemsExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIsNull() {
            addCriterion("CACHE_KEY is null");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIsNotNull() {
            addCriterion("CACHE_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andCacheKeyEqualTo(String value) {
            addCriterion("CACHE_KEY =", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotEqualTo(String value) {
            addCriterion("CACHE_KEY <>", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyGreaterThan(String value) {
            addCriterion("CACHE_KEY >", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyGreaterThanOrEqualTo(String value) {
            addCriterion("CACHE_KEY >=", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLessThan(String value) {
            addCriterion("CACHE_KEY <", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLessThanOrEqualTo(String value) {
            addCriterion("CACHE_KEY <=", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLike(String value) {
            addCriterion("CACHE_KEY like", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotLike(String value) {
            addCriterion("CACHE_KEY not like", value, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyIn(List<String> values) {
            addCriterion("CACHE_KEY in", values, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotIn(List<String> values) {
            addCriterion("CACHE_KEY not in", values, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyBetween(String value1, String value2) {
            addCriterion("CACHE_KEY between", value1, value2, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCacheKeyNotBetween(String value1, String value2) {
            addCriterion("CACHE_KEY not between", value1, value2, "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCatalogsIsNull() {
            addCriterion("CATALOGS is null");
            return (Criteria) this;
        }

        public Criteria andCatalogsIsNotNull() {
            addCriterion("CATALOGS is not null");
            return (Criteria) this;
        }

        public Criteria andCatalogsEqualTo(String value) {
            addCriterion("CATALOGS =", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsNotEqualTo(String value) {
            addCriterion("CATALOGS <>", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsGreaterThan(String value) {
            addCriterion("CATALOGS >", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsGreaterThanOrEqualTo(String value) {
            addCriterion("CATALOGS >=", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsLessThan(String value) {
            addCriterion("CATALOGS <", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsLessThanOrEqualTo(String value) {
            addCriterion("CATALOGS <=", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsLike(String value) {
            addCriterion("CATALOGS like", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsNotLike(String value) {
            addCriterion("CATALOGS not like", value, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsIn(List<String> values) {
            addCriterion("CATALOGS in", values, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsNotIn(List<String> values) {
            addCriterion("CATALOGS not in", values, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsBetween(String value1, String value2) {
            addCriterion("CATALOGS between", value1, value2, "catalogs");
            return (Criteria) this;
        }

        public Criteria andCatalogsNotBetween(String value1, String value2) {
            addCriterion("CATALOGS not between", value1, value2, "catalogs");
            return (Criteria) this;
        }

        public Criteria andContentsIsNull() {
            addCriterion("CONTENTS is null");
            return (Criteria) this;
        }

        public Criteria andContentsIsNotNull() {
            addCriterion("CONTENTS is not null");
            return (Criteria) this;
        }

        public Criteria andContentsEqualTo(String value) {
            addCriterion("CONTENTS =", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsNotEqualTo(String value) {
            addCriterion("CONTENTS <>", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsGreaterThan(String value) {
            addCriterion("CONTENTS >", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENTS >=", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsLessThan(String value) {
            addCriterion("CONTENTS <", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsLessThanOrEqualTo(String value) {
            addCriterion("CONTENTS <=", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsLike(String value) {
            addCriterion("CONTENTS like", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsNotLike(String value) {
            addCriterion("CONTENTS not like", value, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsIn(List<String> values) {
            addCriterion("CONTENTS in", values, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsNotIn(List<String> values) {
            addCriterion("CONTENTS not in", values, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsBetween(String value1, String value2) {
            addCriterion("CONTENTS between", value1, value2, "contents");
            return (Criteria) this;
        }

        public Criteria andContentsNotBetween(String value1, String value2) {
            addCriterion("CONTENTS not between", value1, value2, "contents");
            return (Criteria) this;
        }

        public Criteria andStrV1IsNull() {
            addCriterion("STR_V1 is null");
            return (Criteria) this;
        }

        public Criteria andStrV1IsNotNull() {
            addCriterion("STR_V1 is not null");
            return (Criteria) this;
        }

        public Criteria andStrV1EqualTo(String value) {
            addCriterion("STR_V1 =", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1NotEqualTo(String value) {
            addCriterion("STR_V1 <>", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1GreaterThan(String value) {
            addCriterion("STR_V1 >", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1GreaterThanOrEqualTo(String value) {
            addCriterion("STR_V1 >=", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1LessThan(String value) {
            addCriterion("STR_V1 <", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1LessThanOrEqualTo(String value) {
            addCriterion("STR_V1 <=", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1Like(String value) {
            addCriterion("STR_V1 like", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1NotLike(String value) {
            addCriterion("STR_V1 not like", value, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1In(List<String> values) {
            addCriterion("STR_V1 in", values, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1NotIn(List<String> values) {
            addCriterion("STR_V1 not in", values, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1Between(String value1, String value2) {
            addCriterion("STR_V1 between", value1, value2, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV1NotBetween(String value1, String value2) {
            addCriterion("STR_V1 not between", value1, value2, "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV2IsNull() {
            addCriterion("STR_V2 is null");
            return (Criteria) this;
        }

        public Criteria andStrV2IsNotNull() {
            addCriterion("STR_V2 is not null");
            return (Criteria) this;
        }

        public Criteria andStrV2EqualTo(String value) {
            addCriterion("STR_V2 =", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2NotEqualTo(String value) {
            addCriterion("STR_V2 <>", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2GreaterThan(String value) {
            addCriterion("STR_V2 >", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2GreaterThanOrEqualTo(String value) {
            addCriterion("STR_V2 >=", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2LessThan(String value) {
            addCriterion("STR_V2 <", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2LessThanOrEqualTo(String value) {
            addCriterion("STR_V2 <=", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2Like(String value) {
            addCriterion("STR_V2 like", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2NotLike(String value) {
            addCriterion("STR_V2 not like", value, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2In(List<String> values) {
            addCriterion("STR_V2 in", values, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2NotIn(List<String> values) {
            addCriterion("STR_V2 not in", values, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2Between(String value1, String value2) {
            addCriterion("STR_V2 between", value1, value2, "strV2");
            return (Criteria) this;
        }

        public Criteria andStrV2NotBetween(String value1, String value2) {
            addCriterion("STR_V2 not between", value1, value2, "strV2");
            return (Criteria) this;
        }

        public Criteria andFloatV1IsNull() {
            addCriterion("FLOAT_V1 is null");
            return (Criteria) this;
        }

        public Criteria andFloatV1IsNotNull() {
            addCriterion("FLOAT_V1 is not null");
            return (Criteria) this;
        }

        public Criteria andFloatV1EqualTo(BigDecimal value) {
            addCriterion("FLOAT_V1 =", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1NotEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V1 <>", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1GreaterThan(BigDecimal value) {
            addCriterion("FLOAT_V1 >", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V1 >=", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1LessThan(BigDecimal value) {
            addCriterion("FLOAT_V1 <", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V1 <=", value, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1In(List<BigDecimal> values) {
            addCriterion("FLOAT_V1 in", values, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1NotIn(List<BigDecimal> values) {
            addCriterion("FLOAT_V1 not in", values, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOAT_V1 between", value1, value2, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOAT_V1 not between", value1, value2, "floatV1");
            return (Criteria) this;
        }

        public Criteria andFloatV2IsNull() {
            addCriterion("FLOAT_V2 is null");
            return (Criteria) this;
        }

        public Criteria andFloatV2IsNotNull() {
            addCriterion("FLOAT_V2 is not null");
            return (Criteria) this;
        }

        public Criteria andFloatV2EqualTo(BigDecimal value) {
            addCriterion("FLOAT_V2 =", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2NotEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V2 <>", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2GreaterThan(BigDecimal value) {
            addCriterion("FLOAT_V2 >", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V2 >=", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2LessThan(BigDecimal value) {
            addCriterion("FLOAT_V2 <", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOAT_V2 <=", value, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2In(List<BigDecimal> values) {
            addCriterion("FLOAT_V2 in", values, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2NotIn(List<BigDecimal> values) {
            addCriterion("FLOAT_V2 not in", values, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOAT_V2 between", value1, value2, "floatV2");
            return (Criteria) this;
        }

        public Criteria andFloatV2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOAT_V2 not between", value1, value2, "floatV2");
            return (Criteria) this;
        }

        public Criteria andIntV1IsNull() {
            addCriterion("INT_V1 is null");
            return (Criteria) this;
        }

        public Criteria andIntV1IsNotNull() {
            addCriterion("INT_V1 is not null");
            return (Criteria) this;
        }

        public Criteria andIntV1EqualTo(Long value) {
            addCriterion("INT_V1 =", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1NotEqualTo(Long value) {
            addCriterion("INT_V1 <>", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1GreaterThan(Long value) {
            addCriterion("INT_V1 >", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1GreaterThanOrEqualTo(Long value) {
            addCriterion("INT_V1 >=", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1LessThan(Long value) {
            addCriterion("INT_V1 <", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1LessThanOrEqualTo(Long value) {
            addCriterion("INT_V1 <=", value, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1In(List<Long> values) {
            addCriterion("INT_V1 in", values, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1NotIn(List<Long> values) {
            addCriterion("INT_V1 not in", values, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1Between(Long value1, Long value2) {
            addCriterion("INT_V1 between", value1, value2, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV1NotBetween(Long value1, Long value2) {
            addCriterion("INT_V1 not between", value1, value2, "intV1");
            return (Criteria) this;
        }

        public Criteria andIntV2IsNull() {
            addCriterion("INT_V2 is null");
            return (Criteria) this;
        }

        public Criteria andIntV2IsNotNull() {
            addCriterion("INT_V2 is not null");
            return (Criteria) this;
        }

        public Criteria andIntV2EqualTo(Long value) {
            addCriterion("INT_V2 =", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2NotEqualTo(Long value) {
            addCriterion("INT_V2 <>", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2GreaterThan(Long value) {
            addCriterion("INT_V2 >", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2GreaterThanOrEqualTo(Long value) {
            addCriterion("INT_V2 >=", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2LessThan(Long value) {
            addCriterion("INT_V2 <", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2LessThanOrEqualTo(Long value) {
            addCriterion("INT_V2 <=", value, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2In(List<Long> values) {
            addCriterion("INT_V2 in", values, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2NotIn(List<Long> values) {
            addCriterion("INT_V2 not in", values, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2Between(Long value1, Long value2) {
            addCriterion("INT_V2 between", value1, value2, "intV2");
            return (Criteria) this;
        }

        public Criteria andIntV2NotBetween(Long value1, Long value2) {
            addCriterion("INT_V2 not between", value1, value2, "intV2");
            return (Criteria) this;
        }

        public Criteria andDtV3IsNull() {
            addCriterion("DT_V3 is null");
            return (Criteria) this;
        }

        public Criteria andDtV3IsNotNull() {
            addCriterion("DT_V3 is not null");
            return (Criteria) this;
        }

        public Criteria andDtV3EqualTo(Date value) {
            addCriterion("DT_V3 =", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3NotEqualTo(Date value) {
            addCriterion("DT_V3 <>", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3GreaterThan(Date value) {
            addCriterion("DT_V3 >", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3GreaterThanOrEqualTo(Date value) {
            addCriterion("DT_V3 >=", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3LessThan(Date value) {
            addCriterion("DT_V3 <", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3LessThanOrEqualTo(Date value) {
            addCriterion("DT_V3 <=", value, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3In(List<Date> values) {
            addCriterion("DT_V3 in", values, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3NotIn(List<Date> values) {
            addCriterion("DT_V3 not in", values, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3Between(Date value1, Date value2) {
            addCriterion("DT_V3 between", value1, value2, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV3NotBetween(Date value1, Date value2) {
            addCriterion("DT_V3 not between", value1, value2, "dtV3");
            return (Criteria) this;
        }

        public Criteria andDtV4IsNull() {
            addCriterion("DT_V4 is null");
            return (Criteria) this;
        }

        public Criteria andDtV4IsNotNull() {
            addCriterion("DT_V4 is not null");
            return (Criteria) this;
        }

        public Criteria andDtV4EqualTo(Date value) {
            addCriterion("DT_V4 =", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4NotEqualTo(Date value) {
            addCriterion("DT_V4 <>", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4GreaterThan(Date value) {
            addCriterion("DT_V4 >", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4GreaterThanOrEqualTo(Date value) {
            addCriterion("DT_V4 >=", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4LessThan(Date value) {
            addCriterion("DT_V4 <", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4LessThanOrEqualTo(Date value) {
            addCriterion("DT_V4 <=", value, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4In(List<Date> values) {
            addCriterion("DT_V4 in", values, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4NotIn(List<Date> values) {
            addCriterion("DT_V4 not in", values, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4Between(Date value1, Date value2) {
            addCriterion("DT_V4 between", value1, value2, "dtV4");
            return (Criteria) this;
        }

        public Criteria andDtV4NotBetween(Date value1, Date value2) {
            addCriterion("DT_V4 not between", value1, value2, "dtV4");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("CRT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("CRT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(Date value) {
            addCriterion("CRT_TIME =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(Date value) {
            addCriterion("CRT_TIME <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(Date value) {
            addCriterion("CRT_TIME >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(Date value) {
            addCriterion("CRT_TIME <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<Date> values) {
            addCriterion("CRT_TIME in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<Date> values) {
            addCriterion("CRT_TIME not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("UPD_TIME =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("UPD_TIME <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("UPD_TIME >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("UPD_TIME <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_TIME <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("UPD_TIME in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("UPD_TIME not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_TIME not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andTtlIsNull() {
            addCriterion("TTL is null");
            return (Criteria) this;
        }

        public Criteria andTtlIsNotNull() {
            addCriterion("TTL is not null");
            return (Criteria) this;
        }

        public Criteria andTtlEqualTo(Integer value) {
            addCriterion("TTL =", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlNotEqualTo(Integer value) {
            addCriterion("TTL <>", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlGreaterThan(Integer value) {
            addCriterion("TTL >", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlGreaterThanOrEqualTo(Integer value) {
            addCriterion("TTL >=", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlLessThan(Integer value) {
            addCriterion("TTL <", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlLessThanOrEqualTo(Integer value) {
            addCriterion("TTL <=", value, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlIn(List<Integer> values) {
            addCriterion("TTL in", values, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlNotIn(List<Integer> values) {
            addCriterion("TTL not in", values, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlBetween(Integer value1, Integer value2) {
            addCriterion("TTL between", value1, value2, "ttl");
            return (Criteria) this;
        }

        public Criteria andTtlNotBetween(Integer value1, Integer value2) {
            addCriterion("TTL not between", value1, value2, "ttl");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUuidLikeInsensitive(String value) {
            addCriterion("upper(UUID) like", value.toUpperCase(), "uuid");
            return (Criteria) this;
        }

        public Criteria andCacheKeyLikeInsensitive(String value) {
            addCriterion("upper(CACHE_KEY) like", value.toUpperCase(), "cacheKey");
            return (Criteria) this;
        }

        public Criteria andCatalogsLikeInsensitive(String value) {
            addCriterion("upper(CATALOGS) like", value.toUpperCase(), "catalogs");
            return (Criteria) this;
        }

        public Criteria andContentsLikeInsensitive(String value) {
            addCriterion("upper(CONTENTS) like", value.toUpperCase(), "contents");
            return (Criteria) this;
        }

        public Criteria andStrV1LikeInsensitive(String value) {
            addCriterion("upper(STR_V1) like", value.toUpperCase(), "strV1");
            return (Criteria) this;
        }

        public Criteria andStrV2LikeInsensitive(String value) {
            addCriterion("upper(STR_V2) like", value.toUpperCase(), "strV2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated do_not_delete_during_merge Tue May 17 22:12:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CACHE_ITEMS
     *
     * @mbggenerated Tue May 17 22:12:03 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}