package onight.zjfae.ordbgens.app.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_DICTIONARY")
@AllArgsConstructor
@NoArgsConstructor
public class APPDictionary extends APPDictionaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String keyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.KEY_NAME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.KEY_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String keyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.DATA_VALUE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String dataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String platforms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String appVers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.TTL
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Integer ttl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_DICTIONARY.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.KEY_NO
     *
     * @return the value of APP_DICTIONARY.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getKeyNo() {
        return keyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.KEY_NO
     *
     * @param keyNo the value for APP_DICTIONARY.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setKeyNo(String keyNo) {
        this.keyNo = keyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.KEY_NAME
     *
     * @return the value of APP_DICTIONARY.KEY_NAME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.KEY_NAME
     *
     * @param keyName the value for APP_DICTIONARY.KEY_NAME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.KEY_CODE
     *
     * @return the value of APP_DICTIONARY.KEY_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getKeyCode() {
        return keyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.KEY_CODE
     *
     * @param keyCode the value for APP_DICTIONARY.KEY_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.DATA_VALUE
     *
     * @return the value of APP_DICTIONARY.DATA_VALUE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.DATA_VALUE
     *
     * @param dataValue the value for APP_DICTIONARY.DATA_VALUE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setDataValue(String dataValue) {
        this.dataValue = dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.CRT_TIME
     *
     * @return the value of APP_DICTIONARY.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.CRT_TIME
     *
     * @param crtTime the value for APP_DICTIONARY.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.UPD_TIME
     *
     * @return the value of APP_DICTIONARY.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.UPD_TIME
     *
     * @param updTime the value for APP_DICTIONARY.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.PLATFORMS
     *
     * @return the value of APP_DICTIONARY.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getPlatforms() {
        return platforms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.PLATFORMS
     *
     * @param platforms the value for APP_DICTIONARY.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setPlatforms(String platforms) {
        this.platforms = platforms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.APP_VERS
     *
     * @return the value of APP_DICTIONARY.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getAppVers() {
        return appVers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.APP_VERS
     *
     * @param appVers the value for APP_DICTIONARY.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setAppVers(String appVers) {
        this.appVers = appVers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.TTL
     *
     * @return the value of APP_DICTIONARY.TTL
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Integer getTtl() {
        return ttl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.TTL
     *
     * @param ttl the value for APP_DICTIONARY.TTL
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_DICTIONARY.STATUS
     *
     * @return the value of APP_DICTIONARY.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_DICTIONARY.STATUS
     *
     * @param status the value for APP_DICTIONARY.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_DICTIONARY
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPDictionary other = (APPDictionary) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getKeyNo() == null ? other.getKeyNo() == null : this.getKeyNo().equals(other.getKeyNo()))
            && (this.getKeyName() == null ? other.getKeyName() == null : this.getKeyName().equals(other.getKeyName()))
            && (this.getKeyCode() == null ? other.getKeyCode() == null : this.getKeyCode().equals(other.getKeyCode()))
            && (this.getDataValue() == null ? other.getDataValue() == null : this.getDataValue().equals(other.getDataValue()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getPlatforms() == null ? other.getPlatforms() == null : this.getPlatforms().equals(other.getPlatforms()))
            && (this.getAppVers() == null ? other.getAppVers() == null : this.getAppVers().equals(other.getAppVers()))
            && (this.getTtl() == null ? other.getTtl() == null : this.getTtl().equals(other.getTtl()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_DICTIONARY
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getKeyNo() == null) ? 0 : getKeyNo().hashCode());
        result = prime * result + ((getKeyName() == null) ? 0 : getKeyName().hashCode());
        result = prime * result + ((getKeyCode() == null) ? 0 : getKeyCode().hashCode());
        result = prime * result + ((getDataValue() == null) ? 0 : getDataValue().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getPlatforms() == null) ? 0 : getPlatforms().hashCode());
        result = prime * result + ((getAppVers() == null) ? 0 : getAppVers().hashCode());
        result = prime * result + ((getTtl() == null) ? 0 : getTtl().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_DICTIONARY
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyNo=").append(keyNo);
        sb.append(", keyName=").append(keyName);
        sb.append(", keyCode=").append(keyCode);
        sb.append(", dataValue=").append(dataValue);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", platforms=").append(platforms);
        sb.append(", appVers=").append(appVers);
        sb.append(", ttl=").append(ttl);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}