package onight.zjfae.ordbgens.app.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_IFACE_POSTPROC")
@AllArgsConstructor
@NoArgsConstructor
public class APPIfacePostproc extends APPIfacePostprocKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String keyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.GCMD_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String gcmdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.PB_ACTION
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String pbAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.KEY_REX
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String keyRex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.DATE_TYPE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String dateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.FORMAT_PROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String formatProc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.PROC_PARAMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String procParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.SCRIPTS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String scripts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String platforms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String appVers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.PIO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Integer pio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_IFACE_POSTPROC.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.KEY_NO
     *
     * @return the value of APP_IFACE_POSTPROC.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getKeyNo() {
        return keyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.KEY_NO
     *
     * @param keyNo the value for APP_IFACE_POSTPROC.KEY_NO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setKeyNo(String keyNo) {
        this.keyNo = keyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.GCMD_CODE
     *
     * @return the value of APP_IFACE_POSTPROC.GCMD_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getGcmdCode() {
        return gcmdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.GCMD_CODE
     *
     * @param gcmdCode the value for APP_IFACE_POSTPROC.GCMD_CODE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setGcmdCode(String gcmdCode) {
        this.gcmdCode = gcmdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.PB_ACTION
     *
     * @return the value of APP_IFACE_POSTPROC.PB_ACTION
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getPbAction() {
        return pbAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.PB_ACTION
     *
     * @param pbAction the value for APP_IFACE_POSTPROC.PB_ACTION
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setPbAction(String pbAction) {
        this.pbAction = pbAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.KEY_REX
     *
     * @return the value of APP_IFACE_POSTPROC.KEY_REX
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getKeyRex() {
        return keyRex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.KEY_REX
     *
     * @param keyRex the value for APP_IFACE_POSTPROC.KEY_REX
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setKeyRex(String keyRex) {
        this.keyRex = keyRex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.DATE_TYPE
     *
     * @return the value of APP_IFACE_POSTPROC.DATE_TYPE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.DATE_TYPE
     *
     * @param dateType the value for APP_IFACE_POSTPROC.DATE_TYPE
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.FORMAT_PROC
     *
     * @return the value of APP_IFACE_POSTPROC.FORMAT_PROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getFormatProc() {
        return formatProc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.FORMAT_PROC
     *
     * @param formatProc the value for APP_IFACE_POSTPROC.FORMAT_PROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setFormatProc(String formatProc) {
        this.formatProc = formatProc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.PROC_PARAMS
     *
     * @return the value of APP_IFACE_POSTPROC.PROC_PARAMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getProcParams() {
        return procParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.PROC_PARAMS
     *
     * @param procParams the value for APP_IFACE_POSTPROC.PROC_PARAMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setProcParams(String procParams) {
        this.procParams = procParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.SCRIPTS
     *
     * @return the value of APP_IFACE_POSTPROC.SCRIPTS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getScripts() {
        return scripts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.SCRIPTS
     *
     * @param scripts the value for APP_IFACE_POSTPROC.SCRIPTS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setScripts(String scripts) {
        this.scripts = scripts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.CRT_TIME
     *
     * @return the value of APP_IFACE_POSTPROC.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.CRT_TIME
     *
     * @param crtTime the value for APP_IFACE_POSTPROC.CRT_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.UPD_TIME
     *
     * @return the value of APP_IFACE_POSTPROC.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.UPD_TIME
     *
     * @param updTime the value for APP_IFACE_POSTPROC.UPD_TIME
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.PLATFORMS
     *
     * @return the value of APP_IFACE_POSTPROC.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getPlatforms() {
        return platforms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.PLATFORMS
     *
     * @param platforms the value for APP_IFACE_POSTPROC.PLATFORMS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setPlatforms(String platforms) {
        this.platforms = platforms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.APP_VERS
     *
     * @return the value of APP_IFACE_POSTPROC.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getAppVers() {
        return appVers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.APP_VERS
     *
     * @param appVers the value for APP_IFACE_POSTPROC.APP_VERS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setAppVers(String appVers) {
        this.appVers = appVers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.PIO
     *
     * @return the value of APP_IFACE_POSTPROC.PIO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Integer getPio() {
        return pio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.PIO
     *
     * @param pio the value for APP_IFACE_POSTPROC.PIO
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setPio(Integer pio) {
        this.pio = pio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_IFACE_POSTPROC.STATUS
     *
     * @return the value of APP_IFACE_POSTPROC.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_IFACE_POSTPROC.STATUS
     *
     * @param status the value for APP_IFACE_POSTPROC.STATUS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_IFACE_POSTPROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPIfacePostproc other = (APPIfacePostproc) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getKeyNo() == null ? other.getKeyNo() == null : this.getKeyNo().equals(other.getKeyNo()))
            && (this.getGcmdCode() == null ? other.getGcmdCode() == null : this.getGcmdCode().equals(other.getGcmdCode()))
            && (this.getPbAction() == null ? other.getPbAction() == null : this.getPbAction().equals(other.getPbAction()))
            && (this.getKeyRex() == null ? other.getKeyRex() == null : this.getKeyRex().equals(other.getKeyRex()))
            && (this.getDateType() == null ? other.getDateType() == null : this.getDateType().equals(other.getDateType()))
            && (this.getFormatProc() == null ? other.getFormatProc() == null : this.getFormatProc().equals(other.getFormatProc()))
            && (this.getProcParams() == null ? other.getProcParams() == null : this.getProcParams().equals(other.getProcParams()))
            && (this.getScripts() == null ? other.getScripts() == null : this.getScripts().equals(other.getScripts()))
            && (this.getCrtTime() == null ? other.getCrtTime() == null : this.getCrtTime().equals(other.getCrtTime()))
            && (this.getUpdTime() == null ? other.getUpdTime() == null : this.getUpdTime().equals(other.getUpdTime()))
            && (this.getPlatforms() == null ? other.getPlatforms() == null : this.getPlatforms().equals(other.getPlatforms()))
            && (this.getAppVers() == null ? other.getAppVers() == null : this.getAppVers().equals(other.getAppVers()))
            && (this.getPio() == null ? other.getPio() == null : this.getPio().equals(other.getPio()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_IFACE_POSTPROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getKeyNo() == null) ? 0 : getKeyNo().hashCode());
        result = prime * result + ((getGcmdCode() == null) ? 0 : getGcmdCode().hashCode());
        result = prime * result + ((getPbAction() == null) ? 0 : getPbAction().hashCode());
        result = prime * result + ((getKeyRex() == null) ? 0 : getKeyRex().hashCode());
        result = prime * result + ((getDateType() == null) ? 0 : getDateType().hashCode());
        result = prime * result + ((getFormatProc() == null) ? 0 : getFormatProc().hashCode());
        result = prime * result + ((getProcParams() == null) ? 0 : getProcParams().hashCode());
        result = prime * result + ((getScripts() == null) ? 0 : getScripts().hashCode());
        result = prime * result + ((getCrtTime() == null) ? 0 : getCrtTime().hashCode());
        result = prime * result + ((getUpdTime() == null) ? 0 : getUpdTime().hashCode());
        result = prime * result + ((getPlatforms() == null) ? 0 : getPlatforms().hashCode());
        result = prime * result + ((getAppVers() == null) ? 0 : getAppVers().hashCode());
        result = prime * result + ((getPio() == null) ? 0 : getPio().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_IFACE_POSTPROC
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyNo=").append(keyNo);
        sb.append(", gcmdCode=").append(gcmdCode);
        sb.append(", pbAction=").append(pbAction);
        sb.append(", keyRex=").append(keyRex);
        sb.append(", dateType=").append(dateType);
        sb.append(", formatProc=").append(formatProc);
        sb.append(", procParams=").append(procParams);
        sb.append(", scripts=").append(scripts);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", updTime=").append(updTime);
        sb.append(", platforms=").append(platforms);
        sb.append(", appVers=").append(appVers);
        sb.append(", pio=").append(pio);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}