package onight.zjfae.ordbgens.app.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_SYS_PUSHMSG")
@AllArgsConstructor
@NoArgsConstructor
public class APPSysPushmsg extends APPSysPushmsgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.MSG_TITLE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.MSG_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.OPERATOR_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.CONTENTS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.STATUS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.TOTAL_SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer totalSendCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.RECV_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer recvCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer sendCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.INSERTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Date inserttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.UPDATETIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.TARGET_PLATFORM
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String targetPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.MSG_TYPE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.TOKENID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String tokenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.DEVICEID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.TAGS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.EXTRAS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String extras;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.BADGE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer badge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.SOUND
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private String sound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.ANDROID_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer androidReceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.OS_APNS_SENT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer osApnsSent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.OS_MSG_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Integer osMsgReceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.SENDTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_PUSHMSG.REPORTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    private Date reporttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.MSG_TITLE
     *
     * @return the value of APP_SYS_PUSHMSG.MSG_TITLE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.MSG_TITLE
     *
     * @param msgTitle the value for APP_SYS_PUSHMSG.MSG_TITLE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.MSG_ID
     *
     * @return the value of APP_SYS_PUSHMSG.MSG_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.MSG_ID
     *
     * @param msgId the value for APP_SYS_PUSHMSG.MSG_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.OPERATOR_ID
     *
     * @return the value of APP_SYS_PUSHMSG.OPERATOR_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.OPERATOR_ID
     *
     * @param operatorId the value for APP_SYS_PUSHMSG.OPERATOR_ID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.CONTENTS
     *
     * @return the value of APP_SYS_PUSHMSG.CONTENTS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.CONTENTS
     *
     * @param contents the value for APP_SYS_PUSHMSG.CONTENTS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.STATUS
     *
     * @return the value of APP_SYS_PUSHMSG.STATUS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.STATUS
     *
     * @param status the value for APP_SYS_PUSHMSG.STATUS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.TOTAL_SEND_COUNT
     *
     * @return the value of APP_SYS_PUSHMSG.TOTAL_SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getTotalSendCount() {
        return totalSendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.TOTAL_SEND_COUNT
     *
     * @param totalSendCount the value for APP_SYS_PUSHMSG.TOTAL_SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setTotalSendCount(Integer totalSendCount) {
        this.totalSendCount = totalSendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.RECV_COUNT
     *
     * @return the value of APP_SYS_PUSHMSG.RECV_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getRecvCount() {
        return recvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.RECV_COUNT
     *
     * @param recvCount the value for APP_SYS_PUSHMSG.RECV_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setRecvCount(Integer recvCount) {
        this.recvCount = recvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.SEND_COUNT
     *
     * @return the value of APP_SYS_PUSHMSG.SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.SEND_COUNT
     *
     * @param sendCount the value for APP_SYS_PUSHMSG.SEND_COUNT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.INSERTTIME
     *
     * @return the value of APP_SYS_PUSHMSG.INSERTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.INSERTTIME
     *
     * @param inserttime the value for APP_SYS_PUSHMSG.INSERTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.UPDATETIME
     *
     * @return the value of APP_SYS_PUSHMSG.UPDATETIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.UPDATETIME
     *
     * @param updatetime the value for APP_SYS_PUSHMSG.UPDATETIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.TARGET_PLATFORM
     *
     * @return the value of APP_SYS_PUSHMSG.TARGET_PLATFORM
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getTargetPlatform() {
        return targetPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.TARGET_PLATFORM
     *
     * @param targetPlatform the value for APP_SYS_PUSHMSG.TARGET_PLATFORM
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setTargetPlatform(String targetPlatform) {
        this.targetPlatform = targetPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.MSG_TYPE
     *
     * @return the value of APP_SYS_PUSHMSG.MSG_TYPE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.MSG_TYPE
     *
     * @param msgType the value for APP_SYS_PUSHMSG.MSG_TYPE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.TOKENID
     *
     * @return the value of APP_SYS_PUSHMSG.TOKENID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getTokenid() {
        return tokenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.TOKENID
     *
     * @param tokenid the value for APP_SYS_PUSHMSG.TOKENID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setTokenid(String tokenid) {
        this.tokenid = tokenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.DEVICEID
     *
     * @return the value of APP_SYS_PUSHMSG.DEVICEID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.DEVICEID
     *
     * @param deviceid the value for APP_SYS_PUSHMSG.DEVICEID
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.TAGS
     *
     * @return the value of APP_SYS_PUSHMSG.TAGS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.TAGS
     *
     * @param tags the value for APP_SYS_PUSHMSG.TAGS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.EXTRAS
     *
     * @return the value of APP_SYS_PUSHMSG.EXTRAS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getExtras() {
        return extras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.EXTRAS
     *
     * @param extras the value for APP_SYS_PUSHMSG.EXTRAS
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setExtras(String extras) {
        this.extras = extras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.BADGE
     *
     * @return the value of APP_SYS_PUSHMSG.BADGE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getBadge() {
        return badge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.BADGE
     *
     * @param badge the value for APP_SYS_PUSHMSG.BADGE
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setBadge(Integer badge) {
        this.badge = badge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.SOUND
     *
     * @return the value of APP_SYS_PUSHMSG.SOUND
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public String getSound() {
        return sound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.SOUND
     *
     * @param sound the value for APP_SYS_PUSHMSG.SOUND
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setSound(String sound) {
        this.sound = sound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.ANDROID_RECEIVED
     *
     * @return the value of APP_SYS_PUSHMSG.ANDROID_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getAndroidReceived() {
        return androidReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.ANDROID_RECEIVED
     *
     * @param androidReceived the value for APP_SYS_PUSHMSG.ANDROID_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setAndroidReceived(Integer androidReceived) {
        this.androidReceived = androidReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.OS_APNS_SENT
     *
     * @return the value of APP_SYS_PUSHMSG.OS_APNS_SENT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getOsApnsSent() {
        return osApnsSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.OS_APNS_SENT
     *
     * @param osApnsSent the value for APP_SYS_PUSHMSG.OS_APNS_SENT
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setOsApnsSent(Integer osApnsSent) {
        this.osApnsSent = osApnsSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.OS_MSG_RECEIVED
     *
     * @return the value of APP_SYS_PUSHMSG.OS_MSG_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Integer getOsMsgReceived() {
        return osMsgReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.OS_MSG_RECEIVED
     *
     * @param osMsgReceived the value for APP_SYS_PUSHMSG.OS_MSG_RECEIVED
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setOsMsgReceived(Integer osMsgReceived) {
        this.osMsgReceived = osMsgReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.SENDTIME
     *
     * @return the value of APP_SYS_PUSHMSG.SENDTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.SENDTIME
     *
     * @param sendtime the value for APP_SYS_PUSHMSG.SENDTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_PUSHMSG.REPORTTIME
     *
     * @return the value of APP_SYS_PUSHMSG.REPORTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public Date getReporttime() {
        return reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_PUSHMSG.REPORTTIME
     *
     * @param reporttime the value for APP_SYS_PUSHMSG.REPORTTIME
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    public void setReporttime(Date reporttime) {
        this.reporttime = reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_PUSHMSG
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPSysPushmsg other = (APPSysPushmsg) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getMsgTitle() == null ? other.getMsgTitle() == null : this.getMsgTitle().equals(other.getMsgTitle()))
            && (this.getMsgId() == null ? other.getMsgId() == null : this.getMsgId().equals(other.getMsgId()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getContents() == null ? other.getContents() == null : this.getContents().equals(other.getContents()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTotalSendCount() == null ? other.getTotalSendCount() == null : this.getTotalSendCount().equals(other.getTotalSendCount()))
            && (this.getRecvCount() == null ? other.getRecvCount() == null : this.getRecvCount().equals(other.getRecvCount()))
            && (this.getSendCount() == null ? other.getSendCount() == null : this.getSendCount().equals(other.getSendCount()))
            && (this.getInserttime() == null ? other.getInserttime() == null : this.getInserttime().equals(other.getInserttime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getTargetPlatform() == null ? other.getTargetPlatform() == null : this.getTargetPlatform().equals(other.getTargetPlatform()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getTokenid() == null ? other.getTokenid() == null : this.getTokenid().equals(other.getTokenid()))
            && (this.getDeviceid() == null ? other.getDeviceid() == null : this.getDeviceid().equals(other.getDeviceid()))
            && (this.getTags() == null ? other.getTags() == null : this.getTags().equals(other.getTags()))
            && (this.getExtras() == null ? other.getExtras() == null : this.getExtras().equals(other.getExtras()))
            && (this.getBadge() == null ? other.getBadge() == null : this.getBadge().equals(other.getBadge()))
            && (this.getSound() == null ? other.getSound() == null : this.getSound().equals(other.getSound()))
            && (this.getAndroidReceived() == null ? other.getAndroidReceived() == null : this.getAndroidReceived().equals(other.getAndroidReceived()))
            && (this.getOsApnsSent() == null ? other.getOsApnsSent() == null : this.getOsApnsSent().equals(other.getOsApnsSent()))
            && (this.getOsMsgReceived() == null ? other.getOsMsgReceived() == null : this.getOsMsgReceived().equals(other.getOsMsgReceived()))
            && (this.getSendtime() == null ? other.getSendtime() == null : this.getSendtime().equals(other.getSendtime()))
            && (this.getReporttime() == null ? other.getReporttime() == null : this.getReporttime().equals(other.getReporttime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_PUSHMSG
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getMsgTitle() == null) ? 0 : getMsgTitle().hashCode());
        result = prime * result + ((getMsgId() == null) ? 0 : getMsgId().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTotalSendCount() == null) ? 0 : getTotalSendCount().hashCode());
        result = prime * result + ((getRecvCount() == null) ? 0 : getRecvCount().hashCode());
        result = prime * result + ((getSendCount() == null) ? 0 : getSendCount().hashCode());
        result = prime * result + ((getInserttime() == null) ? 0 : getInserttime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getTargetPlatform() == null) ? 0 : getTargetPlatform().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getTokenid() == null) ? 0 : getTokenid().hashCode());
        result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
        result = prime * result + ((getTags() == null) ? 0 : getTags().hashCode());
        result = prime * result + ((getExtras() == null) ? 0 : getExtras().hashCode());
        result = prime * result + ((getBadge() == null) ? 0 : getBadge().hashCode());
        result = prime * result + ((getSound() == null) ? 0 : getSound().hashCode());
        result = prime * result + ((getAndroidReceived() == null) ? 0 : getAndroidReceived().hashCode());
        result = prime * result + ((getOsApnsSent() == null) ? 0 : getOsApnsSent().hashCode());
        result = prime * result + ((getOsMsgReceived() == null) ? 0 : getOsMsgReceived().hashCode());
        result = prime * result + ((getSendtime() == null) ? 0 : getSendtime().hashCode());
        result = prime * result + ((getReporttime() == null) ? 0 : getReporttime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_PUSHMSG
     *
     * @mbggenerated Thu May 26 19:21:32 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgTitle=").append(msgTitle);
        sb.append(", msgId=").append(msgId);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", contents=").append(contents);
        sb.append(", status=").append(status);
        sb.append(", totalSendCount=").append(totalSendCount);
        sb.append(", recvCount=").append(recvCount);
        sb.append(", sendCount=").append(sendCount);
        sb.append(", inserttime=").append(inserttime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", targetPlatform=").append(targetPlatform);
        sb.append(", msgType=").append(msgType);
        sb.append(", tokenid=").append(tokenid);
        sb.append(", deviceid=").append(deviceid);
        sb.append(", tags=").append(tags);
        sb.append(", extras=").append(extras);
        sb.append(", badge=").append(badge);
        sb.append(", sound=").append(sound);
        sb.append(", androidReceived=").append(androidReceived);
        sb.append(", osApnsSent=").append(osApnsSent);
        sb.append(", osMsgReceived=").append(osMsgReceived);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", reporttime=").append(reporttime);
        sb.append("]");
        return sb.toString();
    }
}