package onight.zjfae.ordbgens.app.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_SYS_BLACKWORD")
@AllArgsConstructor
@NoArgsConstructor
public class APPSysBlackword extends APPSysBlackwordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_SYS_BLACKWORD.WORDS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    private String words;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_SYS_BLACKWORD.WORDS
     *
     * @return the value of APP_SYS_BLACKWORD.WORDS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public String getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_SYS_BLACKWORD.WORDS
     *
     * @param words the value for APP_SYS_BLACKWORD.WORDS
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    public void setWords(String words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_BLACKWORD
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPSysBlackword other = (APPSysBlackword) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getWords() == null ? other.getWords() == null : this.getWords().equals(other.getWords()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_BLACKWORD
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getWords() == null) ? 0 : getWords().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_SYS_BLACKWORD
     *
     * @mbggenerated Thu May 19 19:22:29 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", words=").append(words);
        sb.append("]");
        return sb.toString();
    }
}